### ISSUE TITLE
run gtlike

### ISSUE THREAD

**Issue by laofei177** [fermi-lat/Fermitools-conda#104]
4FGL J2212.4+0708:
norm: 5.53552 +/- 0.49137
alpha: 2.35346 +/- 0.119901
beta: 5.68449 +/- 1.12019
Eb: 1.50802
TS value: 296.246
Flux: 4.16231e-09 +/- 7.63463e-10 photons/cm^2/s

4FGL J2212.6+2800:
Prefactor: 1.56398
Index: 2.16579
Scale: 1840.07
Flux: 7.20244e-09 photons/cm^2/s

I found that some sources have "TS value", some sources don't have "TS value", does it implies that the value is very small? I don't understand it. Here, I sincerely appreciate to you.

**Comment by kerrm** [comment]
It seems it is because this source was not fit during the analysis.  Try freeing at least one of its parameters in the source model and see if that works.
