### ISSUE TITLE
Fermitools installation in SLAC SDF slurm batch system

### ISSUE THREAD

**Issue by astro-fermi** [fermi-lat/Fermitools-conda#106]
Hi,

I am trying to install the latest version of FermiTools in the slurm batch system of SLAC. They have centOS machines. I was using older python 2 version of FermiTools without any problem. I now tried the latest version using the following command

conda create -n fermi -c conda-forge -c fermi fermitools python=3

The installation was successful. However, when I tried to activate the environment by running 'conda activate fermi', I face the following error:
-------------------------
Error in <UnknownClass::FindDynamicLibrary>: libRIO[.so | .dll | .dylib | .sl | .dl | .a] does not exist in /sdf/sw/gcc-4.8.5/openmpi-4.0.4/lib:.:/sdf/home/v/XXXX/miniconda3/envs/fermi/lib/root/cint/cint/stl:/sdf/home/XXXX/miniconda3/envs/fermi/lib/root/cint/cint/include:/sdf/home/v/XXXX/miniconda3/envs/fermi/lib/fermitools/:/lib64/tls/x86_64:/lib64/tls:/lib64/x86_64:/lib64:/usr/lib64/tls/x86_64:/usr/lib64/tls:/usr/lib64/x86_64:/usr/lib64
Error in <UnknownClass::FindDynamicLibrary>: libCling[.so | .dll | .dylib | .sl | .dl | .a] does not exist in /sdf/sw/gcc-4.8.5/openmpi-4.0.4/lib:.:/sdf/home/v/XXXX/miniconda3/envs/fermi/lib/root/cint/cint/stl:/sdf/home/v/XXXX/miniconda3/envs/fermi/lib/root/cint/cint/include:/sdf/home/v/XXXX/miniconda3/envs/fermi/lib/fermitools/:/lib64/tls/x86_64:/lib64/tls:/lib64/x86_64:/lib64:/usr/lib64/tls/x86_64:/usr/lib64/tls:/usr/lib64/x86_64:/usr/lib64
Fatal in <TROOT::InitInterpreter>: cannot load symbol /sdf/home/v/XXXX/miniconda3/envs/fermi/bin/root.exe: undefined symbol: CreateInterpreter
-------------------------
I suspect it has something to do with centOS and ROOT but don't know for sure.

Thanks in advance.

**Comment by jasercion** [comment]
I think this may be related to issues we're seeing here: https://github.com/fermi-lat/Fermitools-conda/issues/102
I'll look into this and post once I have some updates.  Thanks for the report!

**Comment by donhorner** [comment]
We have a development version of the Fermitools that we hope to release soon that should fix most installation problems because we removed the ROOT package, which was the source of many of these issues. If you like to test it, you can install the dev version with the command:
`conda create -n fermitools-2.1.30 -c conda-forge -c fermi/label/dev fermitools=2.1.30`
