### ISSUE TITLE
/bin/sh time command not found

### ISSUE THREAD

**Issue by Ashwani-88** [fermi-lat/Fermitools-conda#108]
Hi,
I am getting the following error when I run Fermi sciencetool likelihood analysis using python on cluster via submitting job on SLURM ( a job scheduler).

"/bin/sh time command not found"

However, when I submit a job for fermipy analysis everything works fine.
Also when I run Fermi sciencetool analysis in terminal on cluster it runs without any error.

**Comment by Areustle** [comment]
It may be that your cluster doesn't have this standard Unix utility on all it's nodes. Time is often also provided by the shell, if you have no source providing it I _expect_ you can install it in your fermitools conda environment by installing it from conda-forge: 

conda install -n fermi -c conda-forge time

Assuming your environment is named 'fermi'

**Comment by Ashwani-88** [comment]
Dear Alex,
It is working now.
Thanks for your help.

Regards,
Ashwani Pandey

Post-doctoral Fellow
Indian Institute of Astrophysics (IIA),
II Block, Koramangala,
Bengaluru 560 034, India
Email: ***@***.***, ***@***.***
Mobile: +91-9808530721
Webpage: http://www.iiap.res.in/people/personnel/ashwani.pandey
