### ISSUE TITLE
Increase like.fit process

### ISSUE THREAD

**Issue by Ashwani-88** [fermi-lat/Fermitools-conda#109]
Hi,
I am analysing Fermi LAT 10 years data of a source using fermi sciencetools in a cluster as a serial job.  
1) Is there any way of speeding up the like.fit process?
As model fitting took more than a day and it is still working.
2) Can using a node with multiple cores  increase the process?
3) what is the use of like.optimize?
Thanks in advance!!!

**Comment by nmirabal** [comment]
There is no way to skip the fitting process. More computing power will certainly help. Optimize is just another step in the fitting process. One suggestion is to go through a two-step fitting like the one described in the "Run the Likelihood Analysis" subsection in the following link
https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/extended/extended.html

**Comment by Ashwani-88** [comment]
Thank you for your response and suggestion. 
I have one more query. 
Can I fit a long timescale data (over a year timescale) using a binned likelihood and use the same best-fitted model file to generate light curves with one day binning but using unbinned likelihood analysis?

**Comment by nmirabal** [comment]
Please take a look at the like_lc.pl  script for some guidance on time series. 
https://fermi.gsfc.nasa.gov/ssc/data/analysis/user/

**Comment by Ashwani-88** [comment]
Thanks!!
