### ISSUE TITLE
Use of like.optimize

### ISSUE THREAD

**Issue by Ashwani-88** [fermi-lat/Fermitools-conda#110]
Hi,
I just started fermi data analisis.
In the fermi data analisis page the use of like.optimize is not given.
Could you tell for what purpose and at what step we should use like.optimize?
Can I use it before the first fit ?

Thanks!!

Ashwani

**Comment by nmirabal** [comment]
like.optimize() performs an automatic optimization of the ROI. It is not always required, but it should be used before running like.fit(). It can be included as an extra step just by typing a line like.optimize() before like.fit(..) in the following tutorial

https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/python_tutorial.html
