### ISSUE TITLE
Broken MINUIT link in gtlike documentation

### ISSUE THREAD

**Issue by janvalqui** [fermi-lat/Fermitools-conda#114]
I am searching for MINUIT documentation, but I see that I don't have permission to access the MINUIT webpage cited in the [gtlike documentation](https://raw.githubusercontent.com/fermi-lat/fermitools-fhelp/master/gtlike.txt). It would seem that the MINUIT link is broken on the CERN side.

**Comment by donhorner** [comment]
Thanks for pointing that out.  It looks like CERN is really burying the original MINUIT.  I think I'll change the URL to the MINUIT page for the ROOT library (https://root.cern.ch/doc/master/group__MinuitOld.html) which is how the Fermitools gets MINUIT anyway or the PDF document that still seems to be available. (https://root.cern.ch/download/minuit.pdf).

**Comment by janvalqui** [comment]
Thanks very much, Don!
