### ISSUE TITLE
Error while activating fermi in Mac OS terminal(Mac OS Monterey 12.1).

### ISSUE THREAD

**Issue by parth161** [fermi-lat/Fermitools-conda#116]
I am trying to activate fermi using command `Conda activate fermi` after that its showing following message. How do I resolve following errors...

`input_line_1:1:2: **error**: module 'Darwin' uses additional module map
      '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/mach_machine.modulemap'
      used when the module was built
#include <new>
 ^
input_line_1:1:2: note: imported by module 'std' in '/opt/anaconda3/envs/fermi/lib/std.pcm'
Warning in cling::IncrementalParser::CheckABICompatibility():
  Failed to extract C++ standard library version.
Warning in cling::IncrementalParser::CheckABICompatibility():
  Possible C++ standard library mismatch, compiled with _LIBCPP_ABI_VERSION '1'
  Extraction of runtime standard library version was: ''
input_line_2:1:2: **error**: module 'Darwin' uses additional module map
      '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/mach_machine.modulemap'
      used when the module was built
#include "cling/Interpreter/RuntimeUniverse.h"
 ^
input_line_2:1:2: note: imported by module 'std' in '/opt/anaconda3/envs/fermi/lib/std.pcm'
input_line_2:1:2: note: imported by module 'Cling_Runtime' in
      '/opt/anaconda3/envs/fermi/lib/Cling_Runtime.pcm'
Failed to load module std
Failed to load module std
Failed to load module Cling_Runtime
In file included from input_line_7:36:
In file included from /opt/anaconda3/envs/fermi/bin/../include/c++/v1/cassert:20:
In file included from /opt/anaconda3/envs/fermi/etc//cling/lib/clang/5.0.0/include/assert.h:8:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/assert.h:69:26: **error**: expected function body after function declarator
void abort(void) __dead2 __cold;
                         ^
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking function '_GLOBAL__sub_I_cling_module_12'!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?

 *** Break *** segmentation violation
[/usr/lib/system/libsystem_platform.dylib] _sigtramp (no debug info)
[<unknown binary>] (no debug info)
[/opt/anaconda3/envs/fermi/lib/libCling.6.22.06.so] cling::Value::isVoid() const (no debug info)
[/opt/anaconda3/envs/fermi/lib/libCling.6.22.06.so] TCling::ProcessLine(char const*, TInterpreter::EErrorCode*) (no debug info)
[/opt/anaconda3/envs/fermi/lib/libRint.6.22.06.so] TRint::ProcessLineNr(char const*, char const*, int*) (no debug info)
[/opt/anaconda3/envs/fermi/lib/libRint.6.22.06.so] TRint::HandleTermInput() (no debug info)
[/opt/anaconda3/envs/fermi/lib/libCore.6.22.06.so] TUnixSystem::CheckDescriptors() (no debug info)
[/opt/anaconda3/envs/fermi/lib/libCore.6.22.06.so] TUnixSystem::DispatchOneEvent(bool) (no debug info)
[/opt/anaconda3/envs/fermi/lib/libCore.6.22.06.so] TSystem::InnerLoop() (no debug info)
[/opt/anaconda3/envs/fermi/lib/libCore.6.22.06.so] TSystem::Run() (no debug info)
[/opt/anaconda3/envs/fermi/lib/libCore.6.22.06.so] TApplication::Run(bool) (no debug info)
[/opt/anaconda3/envs/fermi/lib/libRint.6.22.06.so] TRint::Run(bool) (no debug info)
[/opt/anaconda3/envs/fermi/bin/root.exe] main (no debug info)
[/usr/lib/dyld] start (no debug info)
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?`

**Comment by adonath** [comment]
I also get the exact same error:
```
input_line_1:1:2: error: module 'Darwin' uses additional module map '/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/machine.modulemap' used when the module was built
#include <new>
 ^
input_line_1:1:2: note: imported by module 'std' in '/Users/adonath/software/mambaforge/envs/fermi/lib/std.pcm'
Warning in cling::IncrementalParser::CheckABICompatibility():
  Failed to extract C++ standard library version.
Warning in cling::IncrementalParser::CheckABICompatibility():
  Possible C++ standard library mismatch, compiled with _LIBCPP_ABI_VERSION '1'
  Extraction of runtime standard library version was: ''
input_line_2:1:2: error: module 'Darwin' uses additional module map '/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/machine.modulemap' used when the module was built
#include "cling/Interpreter/RuntimeUniverse.h"
 ^
input_line_2:1:2: note: imported by module 'std' in '/Users/adonath/software/mambaforge/envs/fermi/lib/std.pcm'
input_line_2:1:2: note: imported by module 'Cling_Runtime' in '/Users/adonath/software/mambaforge/envs/fermi/lib/Cling_Runtime.pcm'
Failed to load module std
Failed to load module std
Failed to load module Cling_Runtime
In file included from input_line_7:36:
In file included from /Users/adonath/software/mambaforge/envs/fermi/bin/../include/c++/v1/cassert:20:
In file included from /Users/adonath/software/mambaforge/envs/fermi/etc//cling/lib/clang/5.0.0/include/assert.h:8:
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/assert.h:69:26: error: expected function body after function declarator
void abort(void) __dead2 __cold;
                         ^
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking function '_GLOBAL__sub_I_cling_module_12'!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?

 *** Break *** segmentation violation
[/usr/lib/system/libsystem_platform.dylib] _sigtramp (no debug info)
[<unknown binary>] (no debug info)
[<unknown binary>] (no debug info)
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
```
Here is the output of `conda info`:
```
     active environment : fermi
    active env location : /Users/adonath/software/mambaforge/envs/fermi
            shell level : 2
       user config file : /Users/adonath/.condarc
 populated config files : /Users/adonath/software/mambaforge/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __osx=11.6=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/adonath/software/mambaforge  (writable)
      conda av data dir : /Users/adonath/software/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/adonath/software/mambaforge/pkgs
                          /Users/adonath/.conda/pkgs
       envs directories : /Users/adonath/software/mambaforge/envs
                          /Users/adonath/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.7 Darwin/20.6.0 OSX/11.6
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```
However the environment and tools I tried seem to work after.

**Comment by donhorner** [comment]
Sorry, no one has gotten back to you yet. This seems to be a problem with the ROOT package and the latest version of Xcode.  You can find similar error reports on the [ROOT forum](https://root-forum.cern.ch/t/problem-with-root-on-macos-error-module-darwin-uses-additional-module-map/47443).  We're working on updating the Fermitools to fix this issue. 

You can get rid of the errors by downgrading Xcode. You should be able to run '/usr/bin/xcodebuild -version' to see what version you have, and if it is the latest one, go to something like https://xcodereleases.com/ to download and install an earlier version. All you need to do is remove or rename the Xcode app in /Applications and install the older one.  I would suggest version 13.0.

**Comment by emmaow** [comment]
Hi, I am trying to install the fermitooks in mac os v12.1 and have exactly the same problem. I am using /usr/bin/xcodebuild -version:
Xcode 13.0
Build version 13A233

Is there any other work around I can try? thanks! 


Here my output of conda info:

     active environment : fermi
    active env location : /opt/anaconda3/envs/fermi
            shell level : 1
       user config file : /Users/emmita/.condarc
 populated config files : /Users/emmita/.condarc
          conda version : 4.11.0
    conda-build version : 3.21.5
         python version : 3.9.7.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/anaconda3  (writable)
      conda av data dir : /opt/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/sherpa/osx-64
                          https://conda.anaconda.org/sherpa/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/astropy/osx-64
                          https://conda.anaconda.org/astropy/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/cta-observatory/osx-64
                          https://conda.anaconda.org/cta-observatory/noarch
          package cache : /opt/anaconda3/pkgs
                          /Users/emmita/.conda/pkgs
       envs directories : /opt/anaconda3/envs
                          /Users/emmita/.conda/envs
               platform : osx-64
             user-agent : conda/4.11.0 requests/2.26.0 CPython/3.9.7 Darwin/21.1.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False

**Comment by emmaow** [comment]
Problem solved: I installed version 13.0 but used xcode-select --install which installed 13.2 for the command line tools. In case it is useful for someone else, using this: [https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_for_Xcode_13/Command_Line_Tools_for_Xcode_13.dmg 241](https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_for_Xcode_13/Command_Line_Tools_for_Xcode_13.dmg)
worked.

**Comment by donhorner** [comment]
We have a development version of the Fermitools that we hope to release soon that should permanently fix this problem because we removed ROOT altogether.  If you like to test it, you can install the dev version with the command:
`conda create -n fermitools-2.1.30 -c conda-forge -c fermi/label/dev fermitools=2.1.30 `
It should also install much faster.

**Comment by emmaow** [comment]
Thanks! had to link libgsl.25.dylib:
ln -s /opt/anaconda3/pkgs/gsl-2.6-h71c5fe9_2/lib/libgsl.25.dylib  /opt/anaconda3/envs/fermitools-2.1.30/lib/ 
to use it with fermipy, but otherwise it works
