### ISSUE TITLE
Not able to load gtburst

### ISSUE THREAD

**Issue by ShabnamIyyani** [fermi-lat/Fermitools-conda#117]
###### I have installed the fermi science tools within the environment of threeML. In this environment when I try to open the gtburst, I get the following error:
Loading pyBurstAnalysisGUI v. 03-00-00p0 
WARNING: version mismatch between CFITSIO header (v3.47) and linked library (v3.46).

....... done 
Traceback (most recent call last):
  File "/Users/shabnamiyyani/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/fermitools/gtburst.py", line 130, in handle_exception
    return method(*args, **kwargs)
  File "/Users/shabnamiyyani/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/fermitools/gtburst.py", line 578, in main
    self.root = Tk()
  File "/Users/shabnamiyyani/opt/miniconda3/envs/threeML/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable tk.tcl in the following directories: 
    /Users/shabnamiyyani/opt/miniconda3/envs/threeML/lib/tcl8.6/tk8.6 /Users/shabnamiyyani/opt/miniconda3/envs/threeML/lib/tcl8.6/tk8.6/Resources/Scripts /Users/shabnamiyyani/opt/miniconda3/envs/threeML/lib/tk8.6 /Users/shabnamiyyani/opt/miniconda3/envs/threeML/lib/tk8.6/Resources/Scripts /Users/birby/heasoft-6.29/heasoft-6.29/x86_64-apple-darwin19.6.0/lib/tk8.6 /Users/birby/heasoft-6.29/heasoft-6.29/x86_64-apple-darwin19.6.0/lib/tk8.6/Resources/Scripts /Users/shabnamiyyani/opt/miniconda3/envs/threeML/lib/tk8.6 /Users/shabnamiyyani/opt/miniconda3/envs/lib/tk8.6 /Users/shabnamiyyani/opt/miniconda3/envs/threeML/library

/Users/shabnamiyyani/opt/miniconda3/envs/threeML/lib/tk8.6/tk.tcl: version conflict for package "Tk": have 8.6.6, need exactly 8.6.10
version conflict for package "Tk": have 8.6.6, need exactly 8.6.10
    while executing
"package require -exact Tk  8.6.10"
    (file "/Users/shabnamiyyani/opt/miniconda3/envs/threeML/lib/tk8.6/tk.tcl" line 14)
    invoked from within
"source /Users/shabnamiyyani/opt/miniconda3/envs/threeML/lib/tk8.6/tk.tcl"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list source $file]"

This probably means that tk wasn't installed properly.

###### The versions of the tcl and tk that I have installed are 
conda list tcl
###### Name                    Version                   Build  Channel
tcl                       8.6.10                        2    intel

conda list tk 
###### Name                    Version                   Build  Channel
atk-1.0                   2.36.0               he69c4ee_4    conda-forge
gtk2                      2.24.33              h675d97a_1    conda-forge
tk                        8.6.10               h0419947_1    cctbx202105

**Comment by donhorner** [comment]
The workaround is to edit the /Users/shabnamiyyani/opt/miniconda3/envs/threeML/lib/tk8.6/tk.tcl file to change the version number it requires to the one you have or just comment out the line entirely so it won't check.  The version of Tk doesn't really seem to matter to the tools.  When you run gtburst again, you'll probably get similar error about the Tcl version and can do the same thing to the configuration file it lists.  Then, gtburst should start without problems.

**Comment by ShabnamIyyani** [comment]
After commenting those lines, I do not get that error again. Now, while typing the gtburst command, Xquartz is activated and the window just blinks but I am not able to see the window. Also, no error appears in the terminal.

**Comment by donhorner** [comment]
Sometimes the gtburst window is automatically minimized when it launches.  You might want to check your task bar or dock (depending on your operating system) to see if it's there.
