### ISSUE TITLE
Regarding the installation

### ISSUE THREAD

**Issue by ajaykhoj** [fermi-lat/Fermitools-conda#119]
Hi,

I am trying to install fermitools in Ubuntu 22.04 OS , bu t when i run the command "" conda create -n fermi -c conda-forge -c fermi fermitools python=3 clhep=2.4.4.1"" terminal shuts down. I tried many times but getting same problem. How can i resolve this problem and install it correctly.

Best Regards 
Ajay

**Comment by donhorner** [comment]
I'm sorry no one got back to you @ajaykhoj.  Is this still a problem?

**Comment by ajaykhoj** [comment]
Hi@donhorner,

I have installed fermitools in my machine successfully.
