### ISSUE TITLE
Larger memory usage in pyLikelihood

### ISSUE THREAD

**Issue by jballet** [fermi-lat/Fermitools-conda#12]
I am testing FermiTools 1.0.0 under linux (el7).
I have noted a large memory usage penalty (650 MB) when using pyLikelihood with respect to the previous Science Tools (my reference is ST 11-07-00).
I have not been able to pinpoint the culprit precisely, but here are a few numbers (taken from the DRS output of the "ps v pid" command), which might help.
In both cases python itself took 135 MB, import GtApp led to 165 MB.
import UnbinnedAnalysis then led to 491 MB with the old ST, but 1.30 GB with the new FT.
However the problem does not seem to lie in the pyLikelihood part of the code, because, starting from the naked python (135 MB),
import matplotlib led to 291 MB with the old ST, but 1.06 GB with the new FT.

**Comment by giacomov** [comment]
It might be a different default back end. Try setting the env variable MPLBACKEND to Agg in both cases before entering python. Does that happen anyway? 

On a different note, is the matplotlib version the same in the two cases?

**Comment by jballet** [comment]
I am using matplotlib delivered with the ScienceTools or FermiTools.
It was version 1.5.1 in the ScienceTools, it is 2.1.1 in the FermiTools.
Setting MPLBACKEND to Agg did not change anything on import matplotlib.

**Comment by Areustle** [comment]
Assigning to @jasercion.

**Comment by dagorym** [comment]
Looking at this at bit more, I don't see a big actual memory usage in the examples above.  Here's what I see (from top)

```
command                    VIRT      RES       SHR
python alone               26MB      8.8MB     5.3MB
import GtApp               32MB      12.5MB    7.3MB
import matplotlib          1.06GB    42MB      16.4MB
import UnbinnedAnalysis    1.16GB    75.5MB    42.2MB
```

Now VIRT is just all the memory that "could" be addressed by the program including shared libraries, disk files, etc.  RES is the memory actually used.  SHR is the portion of the RES memory that is shared with other program.  The relevant bit is the RES column.  That's the actual amount of memory being consumed.  If I run little scripts that do the above imports, and look at the output of /usr/bin/time --verbose, the "Maximum resident set size", or the maximum RAM used by the process, corresponds to that RES column.

The VIRT column looks like the values reported initially, at least for UnbinnedAnalysis and matplotlib (the other are actually lower now) but this only corresponds to the potential memory use (if you used every possible command in the python and pyLikelihood libraries), not what is actually used.  So I think this is not as big an issue as was first thought as the actual memory used is fairly small.  There is the potential to have to load up all that other stuff but it will only be invoked if actually used in processing.

**Comment by jballet** [comment]
I am sure you are right. I had tried here to understand whether any part of the memory use could come from the initializations, but the main issue was certainly [Likelihood/90](https://github.com/fermi-lat/Likelihood/issues/90) that you solved yesterday.
