### ISSUE TITLE
CFITSIO ERROR 108: error reading from FITS file

### ISSUE THREAD

**Issue by sunanda15** [fermi-lat/Fermitools-conda#125]
I am getting the following error in gtdiffsp. Kindly suggest something to resolve this issue.
# ************************************************************
# ***   4  gtdiffrsp --- Compute Diffuse response
# ************************************************************
time -p gtdiffrsp evfile=/home/sunanda/mkn421/Enrico/enrico/Txs123/TXS0506+056_test_FRONTBACK_MkTime.fits evtable="EVENTS" scfile=/home/sunanda/mkn421/Enrico/enrico/Txs123/L220825053915D7616F2392_SC00.fits sctable="SC_DATA" srcmdl=/home/sunanda/mkn421/Enrico/enrico/Txs123/TXS0506+056_PowerLaw2_model.xml irfs="P8R3_SOURCE_V3" evclsmin=0 evclass="INDEF" evtype="INDEF" convert=no chatter=2 clobber=yes debug=no gui=no mode="ql"
Caught N3tip12TipExceptionE at the top level: ageBaseE in file "/home/sunanda/mkn421/Enrico/enrico/Data/diffuse/gll_iem_v07.fits" (CFITSIO ERROR 108: error reading from FITS file)
[Message] Warning: An error ocurred, retrying ...
time -p gtdiffrsp evfile=/home/sunanda/mkn421/Enrico/enrico/Txs123/TXS0506+056_test_FRONTBACK_MkTime.fits evtable="EVENTS" scfile=/home/sunanda/mkn421/Enrico/enrico/Txs123/L220825053915D7616F2392_SC00.fits sctable="SC_DATA" srcmdl=/home/sunanda/mkn421/Enrico/enrico/Txs123/TXS0506+056_PowerLaw2_model.xml irfs="P8R3_SOURCE_V3" evclsmin=0 evclass="INDEF" evtype="INDEF" convert=no chatter=2 clobber=yes debug=no gui=no mode="ql"
Caught N3tip12TipExceptionE at the top level: ageBaseE in file "/home/sunanda/mkn421/Enrico/enrico/Data/diffuse/gll_iem_v07.fits" (CFITSIO ERROR 108: error reading from FITS file)
[Message] Warning: An error ocurred, retrying ...
time -p gtdiffrsp evfile=/home/sunanda/mkn421/Enrico/enrico/Txs123/TXS0506+056_test_FRONTBACK_MkTime.fits evtable="EVENTS" scfile=/home/sunanda/mkn421/Enrico/enrico/Txs123/L220825053915D7616F2392_SC00.fits sctable="SC_DATA" srcmdl=/home/sunanda/mkn421/Enrico/enrico/Txs123/TXS0506+056_PowerLaw2_model.xml irfs="P8R3_SOURCE_V3" evclsmin=0 evclass="INDEF" evtype="INDEF" convert=no chatter=2 clobber=yes debug=no gui=no mode="ql"
Caught N3tip12TipExceptionE at the top level: ageBaseE in file "/home/sunanda/mkn421/Enrico/enrico/Data/diffuse/gll_iem_v07.fits" (CFITSIO ERROR 108: error reading from FITS file)
[Message] Warning: An error ocurred, retrying ...
time -p gtdiffrsp evfile=/home/sunanda/mkn421/Enrico/enrico/Txs123/TXS0506+056_test_FRONTBACK_MkTime.fits evtable="EVENTS" scfile=/home/sunanda/mkn421/Enrico/enrico/Txs123/L220825053915D7616F2392_SC00.fits sctable="SC_DATA" srcmdl=/home/sunanda/mkn421/Enrico/enrico/Txs123/TXS0506+056_PowerLaw2_model.xml irfs="P8R3_SOURCE_V3" evclsmin=0 evclass="INDEF" evtype="INDEF" convert=no chatter=2 clobber=yes debug=no gui=no mode="ql"
Caught N3tip12TipExceptionE at the top level: ageBaseE in file "/home/sunanda/mkn421/Enrico/enrico/Data/diffuse/gll_iem_v07.fits" (CFITSIO ERROR 108: error reading from FITS file)
[Message] Warning: An error ocurred, retrying ...
time -p gtdiffrsp evfile=/home/sunanda/mkn421/Enrico/enrico/Txs123/TXS0506+056_test_FRONTBACK_MkTime.fits evtable="EVENTS" scfile=/home/sunanda/mkn421/Enrico/enrico/Txs123/L220825053915D7616F2392_SC00.fits sctable="SC_DATA" srcmdl=/home/sunanda/mkn421/Enrico/enrico/Txs123/TXS0506+056_PowerLaw2_model.xml irfs="P8R3_SOURCE_V3" evclsmin=0 evclass="INDEF" evtype="INDEF" convert=no chatter=2 clobber=yes debug=no gui=no mode="ql"
Caught N3tip12TipExceptionE at the top level: ageBaseE in file "/home/sunanda/mkn421/Enrico/enrico/Data/diffuse/gll_iem_v07.fits" (CFITSIO ERROR 108: error reading from FITS file)
[Message] Warning: An error ocurred, retrying ...

*** Error [Message]: An error ocurred and could not be recovered. Exiting! ***

(fermi) 😍sunanda@sunanda-Vostro-5402😄^C

**Comment by nmirabal** [comment]
Are you running the Enrico software?. This seems connected to the Galactic emission model file that is supposed to be in
/home/sunanda/mkn421/Enrico/enrico/Data/diffuse/gll_iem_v07.fits

Is the file in that location?, does it have the proper read permissions?.

**Comment by sunanda15** [comment]
Yes, I am running the Enrico software. I checked the file location.
time -p gtdiffrsp evfile=/home/sunanda/mkn421/Enrico/enrico/TXS0506+056/TXS0506+056_mytest_FRONTBACK_MkTime.fits evtable="EVENTS" scfile=/home/sunanda/mkn421/Enrico/enrico/TXS0506+056/L220825025405426FC86178_SC00.fits sctable="SC_DATA" srcmdl=/home/sunanda/mkn421/Enrico/enrico/TXS0506+056/TXS0506+056_PowerLaw2_model.xml irfs="P8R3_SOURCE_V3" evclsmin=0 evclass="INDEF" evtype="INDEF" convert=no chatter=2 clobber=yes debug=no gui=no mode="ql"
Caught N3tip12TipExceptionE at the top level: ageBaseE in file "/home/sunanda/mkn421/Enrico/enrico/Data/diffuse/gll_iem_v07.fits" (CFITSIO ERROR 108: error reading from FITS file)
[Message] Warning: An error ocurred, retrying ...
time -p gtdiffrsp evfile=/home/sunanda/mkn421/Enrico/enrico/TXS0506+056/TXS0506+056_mytest_FRONTBACK_MkTime.fits evtable="EVENTS" scfile=/home/sunanda/mkn421/Enrico/enrico/TXS0506+056/L220825025405426FC86178_SC00.fits sctable="SC_DATA" srcmdl=/home/sunanda/mkn421/Enrico/enrico/TXS0506+056/TXS0506+056_PowerLaw2_model.xml irfs="P8R3_SOURCE_V3" evclsmin=0 evclass="INDEF" evtype="INDEF" convert=no chatter=2 clobber=yes debug=no gui=no mode="ql"
Caught N3tip12TipExceptionE at the top level: ageBaseE in file "/home/sunanda/mkn421/Enrico/enrico/Data/diffuse/gll_iem_v07.fits" (CFITSIO ERROR 108: error reading from FITS file)
[Message] Warning: An error ocurred, retrying ...
time -p gtdiffrsp evfile=/home/sunanda/mkn421/Enrico/enrico/TXS0506+056/TXS0506+056_mytest_FRONTBACK_MkTime.fits evtable="EVENTS" scfile=/home/sunanda/mkn421/Enrico/enrico/TXS0506+056/L220825025405426FC86178_SC00.fits sctable="SC_DATA" srcmdl=/home/sunanda/mkn421/Enrico/enrico/TXS0506+056/TXS0506+056_PowerLaw2_model.xml irfs="P8R3_SOURCE_V3" evclsmin=0 evclass="INDEF" evtype="INDEF" convert=no chatter=2 clobber=yes debug=no gui=no mode="ql"
Caught N3tip12TipExceptionE at the top level: ageBaseE in file "/home/sunanda/mkn421/Enrico/enrico/Data/diffuse/gll_iem_v07.fits" (CFITSIO ERROR 108: error reading from FITS file)
[Message] Warning: An error ocurred, retrying ...
time -p gtdiffrsp evfile=/home/sunanda/mkn421/Enrico/enrico/TXS0506+056/TXS0506+056_mytest_FRONTBACK_MkTime.fits evtable="EVENTS" scfile=/home/sunanda/mkn421/Enrico/enrico/TXS0506+056/L220825025405426FC86178_SC00.fits sctable="SC_DATA" srcmdl=/home/sunanda/mkn421/Enrico/enrico/TXS0506+056/TXS0506+056_PowerLaw2_model.xml irfs="P8R3_SOURCE_V3" evclsmin=0 evclass="INDEF" evtype="INDEF" convert=no chatter=2 clobber=yes debug=no gui=no mode="ql"
Caught N3tip12TipExceptionE at the top level: ageBaseE in file "/home/sunanda/mkn421/Enrico/enrico/Data/diffuse/gll_iem_v07.fits" (CFITSIO ERROR 108: error reading from FITS file)
[Message] Warning: An error ocurred, retrying ...
time -p gtdiffrsp evfile=/home/sunanda/mkn421/Enrico/enrico/TXS0506+056/TXS0506+056_mytest_FRONTBACK_MkTime.fits evtable="EVENTS" scfile=/home/sunanda/mkn421/Enrico/enrico/TXS0506+056/L220825025405426FC86178_SC00.fits sctable="SC_DATA" srcmdl=/home/sunanda/mkn421/Enrico/enrico/TXS0506+056/TXS0506+056_PowerLaw2_model.xml irfs="P8R3_SOURCE_V3" evclsmin=0 evclass="INDEF" evtype="INDEF" convert=no chatter=2 clobber=yes debug=no gui=no mode="ql"
Caught N3tip12TipExceptionE at the top level: ageBaseE in file "/home/sunanda/mkn421/Enrico/enrico/Data/diffuse/gll_iem_v07.fits" (CFITSIO ERROR 108: error reading from FITS file)
[Message] Warning: An error ocurred, retrying ...

*** Error [Message]: An error ocurred and could not be recovered. Exiting! ***

**Comment by nmirabal** [comment]
Unfortunately, the FSSC does not provide direct support to enrico software. We would recommend using the FSSC analysis threads listed here https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/. The proper place for Enrico issues appears to be the following https://github.com/gammapy/enrico/issues

**Comment by donhorner** [comment]
The only other thing I would suggest is checking that the IEM file is not corrupted.  If you run md5sum on it, you should get the same checksum as this:
```
% md5sum gll_iem_v07.fits 
df49de7587f5d00cd402d0890a1ee2b7  gll_iem_v07.fits
```

**Comment by nmirabal** [comment]
Diffuse responses are only needed for unbinned analysis. Another way to test would be to run the following analysis thread
https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/likelihood_tutorial.html

Weekly LAT files with precomputed diffuse responses can also be downloaded in the following link
https://heasarc.gsfc.nasa.gov/FTP/fermi/data/lat/weekly/diffuse/

**Comment by sunanda15** [comment]
Thank you so much for your reply. In my case, the IEM file was corrupted.
Now, It is working fine.

**Comment by sunanda15** [comment]
Thank you, Don Horner, for your suggestion.
