### ISSUE TITLE
Getting started fermitools

### ISSUE THREAD

**Issue by Jisans** [fermi-lat/Fermitools-conda#129]
Hello all! How to quickly get started with `fermitools` and `fermipy` to analyze Fermi LAT data?

**Comment by nmirabal** [comment]
Please check out the analysis threads for the Fermitools
https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/

You can also browse the fermipy notebooks in the following link
https://nbviewer.org/github/fermiPy/fermipy-extra/blob/master/notebooks/index.ipynb
