### ISSUE TITLE
Optimize the installation of fermitools

### ISSUE THREAD

**Issue by landriu** [fermi-lat/Fermitools-conda#13]
Hi all,

     we need to have multiple versions of the fermitools installed on a dedicated place,
   so comparisons can be made between the different results for each version.

     I tried to use the --prefix option for conda create, writing such command :

       conda create fermitools=1.0.0 --prefix=$NFS_ZONE/fermitools/1.0.0

    and it generates the fermitools package on this place, occupying 3.2GB
 
  This directory includes also all  needed packages such as astropy for example,
 which occupies at least 900MB  when installed alone.

  We would like to optimize the disk usage for our different local installations
 by taking advantage that many underlying packages use the same version
 (as GLAST_EXT did in the past)

   Would it be possible, during installation, to refer to a previous existing directory,
 and copy only the differing versions ?

 This kind of incremental update would save a lot of disk space.

Thanks in advance,

 David Landriu

PS:   I tried to install first astropy alone, activate this astropy environment and
 launch again the conda create, but it did not take care of this existing astropy,
 and replicated it in the fermitools installation, even when I tried the --use-local option.

**Comment by jasercion** [comment]
Hi @landriu,  I've tried a couple of different methods to implement this in Conda but frankly the Conda system is in no way designed for sharing external dependencies (indeed, the way conda enrvironments are set up it explicitly tries to prevent this from happening.)

We are going to discuss this further at the FSSC but for now your best bet (if saving disk space is critical) would be to compile the tools on your own outside of the conda system.  You could use conda to install all of the dependencies in one location using the 

conda install --only-deps -c conda-forge -c fermi fermitools

command and then point SCons at the install location.  The commands that conda uses to package the tools are in this file (it simply executes this bash script):

https://github.com/fermi-lat/Fermitools-conda/blob/master/build.sh

To do this you will need to install 'fermi-repoman' (to check out the packages) in addition to SCons.  This can be installed via pip.  You may also find some of the information on this page useful:

https://github.com/fermi-lat/Fermitools-conda/wiki/Contributing-to-the-Fermitools

**Comment by Areustle** [comment]
It would only be possible to build a fermitools package with a shared `source activate dependencies` if Fermitools is built outside conda using Joe's suggested method.

**Comment by landriu** [comment]
and could it be possible for FSSC to provide such a short version of fermitools, to be associated
locally by the user with the needed dependencies as another delivery ?
 Dependencies should vary slower than fermitools, I guess, and many versions could work with
same external packages ?

**Comment by Areustle** [comment]
In a sense this short version is available currently in the github source repositories using Joe's suggested method.
To the best of my knowledge it is not possible to provide this in Conda.

Note this is not a use case the FSSC has historically supported for a number of reasons. Dependencies do vary (quickly, more quickly than the fermitools will) and we can only guarantee a version of the tools will work with the all of the specified dependencies. This is why Conda is so powerful; it ensures exact dependencies are always properly managed.

Using a shared dependency model is possible. If the user wishes to build from source via Joe's suggested method. This is internally how we build the tools for Conda, and it relies on the older model used by the internal LAT-team ScienceTools. An existing, local GLAST_EXT directory points to the many shared externals. Version and dependency management is entirely the responsibility of the user.
This method works for site installation, and is still viable, but not the goal of the FermiTools or Conda.

**Comment by Areustle** [comment]
Do you have another package / dependency manager system you're aware of that you prefer? One that has the kind of model you're describing, with shared dependencies in addition to segregated environments? If so that could certainly be something we would expand support to in the future. We have tentative plans to bring the FermiTools to pip for example.

**Comment by Areustle** [comment]
What is your system currently using? An OS manager like yum or apt-get? An HPC manager like SPACK or Environment Modules (or the older 'tap'), or Conan? These are the ones I've heard of.

**Comment by landriu** [comment]
Hi Alex,

    in fact I was using the installer.py from Tom Stephens at SLAC, that I modified to check 
if dependencies were already available on local GLAST_EXT, and just downloaded the necessary 
package provided by SLAC, adapted to our system in Saclay.

 So it was really simple to deal with deliveries on our side, with the benefit of sparing disk space.

**Comment by landriu** [comment]
I think I did a ftp a long time ago : 
     I can give you the sources here :
    *** Original installer.py 
[installer.py.txt](https://github.com/fermi-lat/Fermitools-conda/files/2599906/installer.py.txt)

    *** Modified script : 
[Saclay_local_installer.py.txt](https://github.com/fermi-lat/Fermitools-conda/files/2599916/Saclay_local_installer.py.txt)

**Comment by jasercion** [comment]
I should note: the user should only have to compile once.  This should generate more portable binaries.

**Comment by landriu** [comment]
Hi ,

   I have trained for some months to use the conda environments, which are all stored 
in the conda/envs directory, and it seems if I am not mistaking, that anaconda is doing 
a kind of releases management, not reinstalling the components when already defined.

  We could then consider using conda environments is a solution to this problem .

**Comment by Areustle** [comment]
Hi David, 

I've been working on a system to do exactly this, making development easier for local builds without relying on conda-build. It should be viable for all future releases, as well as our current beta releases 1.3.6 and 1.9.13

https://github.com/fermi-lat/fermi_dev_scripts.

**Comment by Areustle** [comment]
This issue is resolved with the new fermitools 2.2.0 version.
