### ISSUE TITLE
Help of Installation failure

### ISSUE THREAD

**Issue by PepeJoseHU** [fermi-lat/Fermitools-conda#130]
Hello, I want to install fermitools with conda 
using : conda install fermitools / conda install -c conda-forge fermitools
But they both failed with an error: 

Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - fermitools

Current channels:

  - http://ssb.stsci.edu/astroconda/linux-64
  - http://ssb.stsci.edu/astroconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

So does anyone can help with solving this problem? 

I tried 'conda config --append channels conda-forge'  or 'conda config --set restore_free_channel true
' but still not work. Anyone know how to fix that? Thank you very much!

**Comment by PepeJoseHU** [comment]
And I try to search it with 'conda search -f fermi'
But the result just have packages: 
fermipy                        1.0.1  py39hef51801_1  conda-forge         
forestopenfermion              0.0.6    pyhd8ed1ab_1  conda-forge         
ifermi                         0.3.0    pyhd8ed1ab_0  conda-forge         
openfermion                    1.5.1    pyhd8ed1ab_0  conda-forge         
openfermionpsi4                  0.5    pyhd8ed1ab_0  conda-forge         
openfermionpyscf                 0.5    pyhd8ed1ab_0  conda-forge         
r-fermicatsr                     1.4   r42h142f84f_0  pkgs/r 
There is not femitools. So, is there any wrong with my searching?

**Comment by donhorner** [comment]
Installation instruction are available on the [Fermitools wiki](https://github.com/fermi-lat/Fermitools-conda/wiki).

**Comment by PepeJoseHU** [comment]
Dear donhorner,

Do you have any suggestions? I tried with ' conda install -c fermi fermitools=2.2.0' ' conda install -c fermi fermitools=2.1.0' ' conda install -c fermi fermitools=2.0.0' both failed. I have no idea how to install fermitools in my enviroment.

Thanks!

**Comment by donhorner** [comment]
Have you tried the install command given in the documentation?  You should be creating a separate environment for the Fermitools.

**Comment by PepeJoseHU** [comment]
Dear donhorner,

I want to install it in an exist environment, is that possible? Or if there have ways for that? That is the reason I used a specified version of fermitools

Thanks!

**Comment by PepeJoseHU** [comment]
THANKS， i give up.
A new environment is built and it installed already with python 3.9.
Thanks again.

**Comment by nmirabal** [comment]
If you want to keep the environment name next time, it is best to probably best to remove the environment first with 'conda env remove -n ENV_NAME' and redo the installation using the same name.

**Comment by PepeJoseHU** [comment]
@nmirabal,  Not keep the name, just keep these settings in the environment. If just a name, I can make a new environment with the same name.
