### ISSUE TITLE
Running the AnalysisThreads code reports an error

### ISSUE THREAD

**Issue by Jisans** [fermi-lat/Fermitools-conda#131]
hello all,
      code:
```
!ds9 ./data/LAT_GRB_analysis/GRB080916C_counts_map.fits
```
erro 
```
/bin/bash: line 1: ds9: command not found
```
**Note:**
ENV: conda env 
system: ubuntu 20.04 LTS
python v3.9.13 fermitools v2.2.0, fermipy v1.1.6

**Comment by donhorner** [comment]
ds9 is a FITS image viewer commonly used in astronomy. You can download it from [CFA](https://sites.google.com/cfa.harvard.edu/saoimageds9) or install it with package manager.  You can also look at the map with [fv](https://heasarc.gsfc.nasa.gov/docs/software/ftools/fv/fv.html) or really anything that can view FITS files.

**Comment by Jisans** [comment]
I'm sorry, I looked at the ds9 website you posted, and I didn't see ds9 installed with package management tools (for example, conda, pip, etc.)

**Comment by Areustle** [comment]
https://installati.one/ubuntu/20.04/saods9/

**Comment by Jisans** [comment]
Thanks!

**Comment by Jisans** [comment]
Hello,
I get an error when I use the `fv` command in  `Jupyterlab` after installing `fv`, what's the matter?
```
code:
!fv ./data/LAT_GRB_analysis/lc_zmax100.fits

zsh:1: command not found: fv

```
I have no problem typing `fv` in the terminal:
![image](https://user-images.githubusercontent.com/110452095/193279848-e88adb69-8e91-4da4-9a99-47d4093014d3.png)

**Comment by mfacorcoran** [comment]
Hi,

 

It may be that the HEADAS environment was not set before you started the jupyter server.  If that’s the case, quit the server, go to a terminal window and initialize HEASoft

 

% source $HEADAS/headas-init.sh

 

Then start the jupyter server in that terminal window.

 

Best regards

 

Mike Corcoran

 

****************************************************

Dr. Michael F. Corcoran

HEASARC

Goddard Space Flight Center, Code 662

Greenbelt, MD 20771

****************************************************

 

From: Jisans Ayesa ***@***.***>
Reply-To: fermi-lat/Fermitools-conda ***@***.***>
Date: Friday, September 30, 2022 at 9:27 AM
To: fermi-lat/Fermitools-conda ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [fermi-lat/Fermitools-conda] Running the AnalysisThreads code reports an error (Issue #131)

 

Hello,
I get an error when I use the fv command in Jupyterlab after installing fv, what's the matter?
code:
!fv ./data/LAT_GRB_analysis/lc_zmax100.fits
 
zsh:1: command not found: fv
 
I have no problem typing fv in the terminal:

**Comment by Jisans** [comment]
@mfacorcoran There is no HEADAS environment installed in my system, because the installation will affect fertools, there will be two warnings,
```
WARNING: You have LD_LIBRARY_PATH set. This might interfere with the correct functioning of conda and the Fermi ST

WARNING: You have PYTHONPATH set. This might interfere with the correct functioning of conda and the Fermi ST

```

**Comment by Jisans** [comment]
Hello all, Today, after I reinstalled heasoft, I used it, but fv reported an error
```
 fv
application-specific initialization failed: couldn't connect to display ":0"
Error in startup script: couldn't connect to display ":0"
    while executing
"load /home/jian/workspace/heasoft-6.30.1/tcltk/x86_64-pc-linux-gnu-libc2.31/lib/libtk8.6.so Tk"
    ("package ifneeded Tk 8.6.11" script)
    invoked from within
"load /home/jian/workspace/heasoft-6.30.1/tcltk/x86_64-pc-linux-gnu-libc2.31/lib/itk4.1.0/libitk4.1.0.so Itk"
    ("package ifneeded Itk 4.1.0" script)
    invoked from within
"package require Itk"
    (procedure "fvInit" line 11)
    invoked from within
"fvInit"
    ("eval" body line 1)
    invoked from within
"eval fvInit $argv"
    (file "/home/jian/workspace/heasoft-6.30.1/x86_64-pc-linux-gnu-libc2.31/lib/fv/fvInit.tcl" line 18)
```
Why would it report an error?

**Comment by donhorner** [comment]
It's difficult to say exactly why you see that error.  It looks like there's an issue connecting to X-windows. Maybe the DISPLAY environment variable isn't set correctly?

To go back to the previous issues, HEASoft and the Fermitools usually work together without any problems.  The warnings are just given if those environment variable are set at all.

**Comment by Jisans** [comment]
Yes, some basic settings are required when installing HEAsoft. However, these settings will cause warnings to pop up when entering the fermitools environment. I found that these warnings did not affect the work. In addition, I can now use FV, thank you for your help!
