### ISSUE TITLE
fermitools local installation cannot be moved

### ISSUE THREAD

**Issue by landriu** [fermi-lat/Fermitools-conda#14]
Hi all,

     we use the "--prefix" option when calling "conda install fermitools" as we
  need to keep different versions of fermitools, in different directories to apply
  some tests .

   When we try to move a given fermitools version, by giving another name to the directory,
for example renaming 1.0.0-beta to 1.0.0, we get an error message, when doing "source activate" :

    [landriu@sappcfermi] ~ > source activate /dsm/saplxglast/glast/fermitools/1.0.0
   root: can't start ROOT -- check that /dsm/saplxglast/glast/fermitools/1.0.0-beta/bin/root.exe exists!

 and also iostream error when calling gtlike : 

  Error: cannot open file "iostream"  (tmpfile):2:
  *** Interpreter error recovered ***
 .../...

  Is it possible to avoid these problems, so we can manage the different directories
 without being obliged to reinstall fermitools version and reapply possibly done
  modifications on it ?

**Comment by jasercion** [comment]
Have you tried using different conda environments to contain each of the different fermitools versions?  Using those you shouldn't need to move the location of the tools themselves to switch (since you can just activate a different environment).

**Comment by landriu** [comment]
Yes, we can reinstall everything each time we have a modification not corresponding to 
an offical version, but it would have been more convenient just to rename an existing 
installation, to say it is an intermediary delivery, instead restarting the whole process 
each time.

**Comment by jasercion** [comment]
I think I might not be following the workflow properly, so I'd like to clarify:

You wish to install different versions of the tools in different locations, test them, and then use one of those installed versions as a production version?

Are you making additional modifications to the version of the tools installed by Conda?  Or do you have other versions of the tools obtained separately (such as older releases from the FSSC) and the Conda release is just one of many on this system?

Does the production version of the tools need to be in a specific immutable directory?  Or do you just need a way to make sure that the one you wish to use is the current active version?

Is this just on one machine?  Or on a distributed computing environment?

Thanks!

**Comment by landriu** [comment]
For the moment, we have two versions : fermitools-1.0.0 and a modified fermitools-1.0.0-alpha generated from official fermitools-1.0.0 with an update provided by Eric Charles for testing: 
  conda update -c conda-forge -c fermi/label/alpha -c fermi fermitools

  in fact I have tried to apply the update on official  installation and tried to rename it, but it 
 did not give a valid installation, and had to restart from the beginning with the option 
--prefix=fermitools-alpha . (Of course the official version has also to be regenarated in all cases
if still needed). 

 We could imagine we want to keep a modified working environment with some conda updates or other operations : this means that we need to redo the whole thing before storing this installation in a
dedicated place for reuse to compare for example different methods on source detection.

**Comment by jasercion** [comment]
Are the two installations living in their own separate conda environments?  Unfortunately Conda does not allow the renaming of environments themselves.  I'm surprised the update didn't work from the official release to the alpha release, do you happen to have any error output from that?  It shouldn't have to reinstall everything for an update, it should just replace the old Fermitools binary with the new one.  All dependencies should remain the same.

**Comment by landriu** [comment]
HI Joe,
  sorry if I have not been clear enough, but I got at first a valid installation after the update, but
it became unvalid after the renaming and I had to recreate a special version with the new name
--prefix=fermitools-alpha : restarting from the beginning : initial installation + update.
   I have then two different installations fermittols-1.0.0 and fermi-1.0.0-alpha including both their
own dependencies .

**Comment by landriu** [comment]
Hi Jon,

  for some months now, we have adopted the use of conda environments, and then the 
locations  of releases are related to the anaconda installation, and once we have
chosen a consistent place where to put anaconda, there should not be now problems of room .

This topic was due to the fact I was not accustomed to the conda philosophy and had to adapt
coming from my old work organisation.

I think we can then close this issue.
