### ISSUE TITLE
Environment stays after "source deactivate"

### ISSUE THREAD

**Issue by landriu** [fermi-lat/Fermitools-conda#15]
When we do "source activate /dsm/saplxglast/glast/fermitools/1.0.0"
 and source deactivate, the environment stays : FERMI_DIR is still the same,
 and executables can still be called : 

[landriu@sappcfermi] ~ > which gtlike
/usr/bin/which: no gtlike in (/opt/rhel-7.x86_64/gnu/anaconda/5.1.0/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/dsm/saplxglast/home/landriu/bin)
[landriu@sappcfermi] ~ > source activate /dsm/saplxglast/glast/fermitools/1.0.0
(/dsm/saplxglast/glast/fermitools/1.0.0
[landriu@sappcfermi] ~ > which gtlike
/dsm/saplxglast/glast/fermitools/1.0.0/bin/fermitools/gtlike
(/dsm/saplxglast/glast/fermitools/1.0.0)
[landriu@sappcfermi] ~ > source deactivate /dsm/saplxglast/glast/fermitools/1.0.0
[landriu@sappcfermi] ~ > which gtlike
/dsm/saplxglast/glast/fermitools/1.0.0/bin/fermitools/gtlike
[landriu@sappcfermi] ~ >
[landriu@sappcfermi] ~ > env | grep FERMI
FERMI_OLD_PFILES=
FERMI_DIR=/dsm/saplxglast/glast/fermitools/1.0.0/share/fermitools

 .../...

**Comment by jasercion** [comment]
It appears that the deactivate script is not actually being called int his case.  Try running `source deactivate` without any path after it and let me know what the result is (same or otherwise).

**Comment by landriu** [comment]
Hi Joe,

  the behaviour is the same after a  command deactivate without any path : 
[landriu@sappcfermi] ~ > source activate /dsm/saplxglast/glast/fermitools/1.0.0
You have LD_LIBRARY_PATH set. This might interfere with the correct functioning of conda and the Fermi ST
(/dsm/saplxglast/glast/fermitools/1.0.0) 
[landriu@sappcfermi] ~ > which gtlike
/dsm/saplxglast/glast/fermitools/1.0.0/bin/fermitools/gtlike
(/dsm/saplxglast/glast/fermitools/1.0.0) 
[landriu@sappcfermi] ~ > source deactivate

[landriu@sappcfermi] ~ >  which gtlike
/dsm/saplxglast/glast/fermitools/1.0.0/bin/fermitools/gtlike

[landriu@sappcfermi] ~ > env | grep FERMI
FERMI_OLD_PFILES=
FERMI_DIR=/dsm/saplxglast/glast/fermitools/1.0.0/share/fermitools
.../...

**Comment by jasercion** [comment]
Ok.  So it looks like two separate issues are occurring here.  The deactivate command isn't properly sourcing the deactivate script and the script itself isn't fully cleaning up the environment variables.  The second issue will most likely just require some patching to the deactivate scripts but I will need to investigate the first issue a bit and see if I can replicate it here.

**Comment by landriu** [comment]
Hello Joe,

 did you make any progress : the deactivate still does not work with our installation of fermitools-1.0.10, and it seems it could interfere with other packages as vnc which cannot be used on a working
session with fermitools environment activated .

 Thanks

**Comment by jasercion** [comment]
Hi @landriu, is your installation of conda up to date?  Conda made a few changes relatively recently that may affect this.  If it is not, try updating conda and using `conda deactivate`.  Let me know if that throws an error and what that error is.

**Comment by landriu** [comment]
Hi joe,

 this works indeed : 

[landriu@sappcfermi] ~ >
(/dsm/saplxglast/glast/fermitools/last_version) 
[landriu@sappcfermi] ~ > conda deactivate
[landriu@sappcfermi] ~ > 

Thanks for your help

**Comment by landriu** [comment]
but I just saw that gtlike is still pointing to ::
[landriu@sappcfermi] ~ > conda deactivate
[landriu@sappcfermi] ~ > which gtlike
/dsm/saplxglast/glast/fermitools/1.0.10/bin/fermitools/gtlike

  what is defined in my .profile and not : /dsm/saplxglast/glast/fermitools/last_version
that I did  interactively .

  It seems the action is not functional when the environment has been defined in the .profile
and the user cannot refresh his working environment and is obliged to modify it
if he needs to start with empty definitions ..

**Comment by landriu** [comment]
In  fact, if I start whithout defining an environment : 
 
[landriu@sappcfermi] ~ > which gtlike
/usr/bin/which: no gtlike in (/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/dsm/saplxglast/home/landriu/bin)
 
, and do then : 

[landriu@sappcfermi] ~ > source activate /dsm/saplxglast/glast/fermitools/1.0.10
You have LD_LIBRARY_PATH set. This might interfere with the correct functioning of conda and the Fermi ST
(/dsm/saplxglast/glast/fermitools/1.0.10)

 [landriu@sappcfermi] ~ > which gtlike
/dsm/saplxglast/glast/fermitools/1.0.10/bin/fermitools/gtlike

[landriu@sappcfermi] ~ > conda deactivate

[landriu@sappcfermi] ~ > which gtlike
/dsm/saplxglast/glast/fermitools/1.0.10/bin/fermitools/gtlike

   So the problem remains.

**Comment by jasercion** [comment]
Do you get the same result if you use `conda activate` as opposed to `source activate`?

**Comment by landriu** [comment]
yes I got the same result : 



(base) 
[landriu@sappcfermi] ~ > which gtlike
/usr/bin/which: no gtlike in (/opt/rhel-7.x86_64/gnu/anaconda/2019.03/bin:/opt/rhel-7.x86_64/gnu/anaconda/2019.03/condabin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/dsm/saplxglast/home/landriu/bin)
(base) 
[landriu@sappcfermi] ~ > conda activate /dsm/saplxglast/glast/fermitools/1.0.10
(/dsm/saplxglast/glast/fermitools/1.0.10) 
[landriu@sappcfermi] ~ > which gtlike
/dsm/saplxglast/glast/fermitools/1.0.10/bin/fermitools/gtlike
(/dsm/saplxglast/glast/fermitools/1.0.10) 
[landriu@sappcfermi] ~ > conda deactivate
(base) 
[landriu@sappcfermi] ~ > which gtlike
/dsm/saplxglast/glast/fermitools/1.0.10/bin/fermitools/gtlike
(base) 

Moreover, to define conda as a command I had to do : 
conda init , and choose bash 
and now I have the prompt (base) and conda always defined when I log in

Do you know how to exit properly to get back an empty environment ?

Thanks again

**Comment by jasercion** [comment]
Unfortunately with the introduction of `conda init` the `(base)` prompt and `conda` definition is expected behavior.  `conda init` changes your `.bashrc` to automatically source and set up conda when you log in.  To fix this, I'd suggest commenting out the changes it made to that script and encapsulating them in an aliased command that you can run when you want conda to be sourced.  Another command could then be used to deactivate the changes.  

With regards to the initial problem, when you run `conda activate` is an environment variable named `FERMI_OLD_PATH` created?  And if so, is its value the same as your `PATH` before activation?

**Comment by landriu** [comment]
Yes FERMI_OLD_PATH is created, and I have then  : 

[landriu@sappcfermi] ~ > echo $FERMI_OLD_PATH | awk -F: '{for (i=1;i<NF;i++){print $i}}'
/opt/rhel-7.x86_64/gnu/anaconda/2019.03/condabin
/dsm/saplxglast/glast/fermitools/1.0.10/bin
/opt/rhel-7.x86_64/gnu/anaconda/2019.03/condabin
/home/landriu/builds/Healpix_3.30/src/cxx/generic_gcc/bin
/usr/lib64/qt-3.3/bin
/usr/local/bin
/usr/bin
/usr/local/sbin
/usr/sbin
/opt/puppetlabs/bin
(/dsm/saplxglast/glast/fermitools/1.0.10) 
[landriu@sappcfermi] ~ >    

and I had before activation : 

[landriu@sappcfermi] ~ > echo $PATH | awk -F: '{for (i=1;i<NF;i++){print $i}}'
/opt/rhel-7.x86_64/gnu/anaconda/2019.03/bin
/opt/rhel-7.x86_64/gnu/anaconda/2019.03/condabin
/home/landriu/builds/Healpix_3.30/src/cxx/generic_gcc/bin
/usr/lib64/qt-3.3/bin
/usr/local/bin
/usr/bin
/usr/local/sbin
/usr/sbin
/opt/puppetlabs/bin
(base) 
[landriu@sappcfermi] ~ > 

   So we have : /dsm/saplxglast/glast/fermitools/1.0.10/bin in FERMI_OLD_PATH, we did have in
PATH, if I read well

**Comment by landriu** [comment]
we did not have in PATH (excuse me)

**Comment by jasercion** [comment]
Thanks!  I think this pinpoints the problem.  `FERMI_OLD_PATH` is meant to capture the users old `PATH` variable so that it can be reset upon deactivation.  Clearly it is doing this after `conda` already modifies the `PATH`.  

I'll update this and get a fix out in the next patch.  Apologies for the delay in getting this fixed, thank you for pinging me again about it.

**Comment by landriu** [comment]
That's  a good point indeed.

 Thank you very much,

Cheers,

   David Landriu
________________________________
De : jasercion [notifications@github.com]
Envoyé : lundi 29 juillet 2019 17:13
À : fermi-lat/Fermitools-conda
Cc : Landriu David; Mention
Objet : Re: [fermi-lat/Fermitools-conda] Environment stays after "source deactivate" (#15)


Thanks! I think this pinpoints the problem. FERMI_OLD_PATH is meant to capture the users old PATH variable so that it can be reset upon deactivation. Clearly it is doing this after conda already modifies the PATH.

I'll update this and get a fix out in the next patch. Apologies for the delay in getting this fixed, thank you for pinging me again about it.

**Comment by jasercion** [comment]
Just found this out.  @landriu to disable conda from automatically starting up when you launch your shell run `conda config --set auto_activate_base false`.  This will prevent conda from auto activating the `(base)` environment.

**Comment by landriu** [comment]
It works indeed, I can close this issue
 
  Thank you again.

   Cheers
