### ISSUE TITLE
Doubts on performing pulsar phased analysis

### ISSUE THREAD

**Issue by TheCriticalSpan** [fermi-lat/Fermitools-conda#150]
Hey everyone!
So I'm trying to perform spectral analysis for the on- and off-phase components of a pulsars emission. I know you can define components in your config file based on pulsar phase through the arguments phasemin and phasemax, although this requires an ft1 .fits event file which a pulsar phase column for your data. I already have a pulsar phase column, but can't figure out where I should be inputting the ft1 file in the config to preform the component analysis. I have tried setting the evfile argument to the ft1 file that has a phase column and running the setup that way but that gives me an index error. Is there maybe an optional argument through which I'm supposed to link the event file to the config that I'm just missing?
Any help would be appreciated!

**Comment by donhorner** [comment]
Have you looked at @kerrm's video tutorial on doing pulsar analysis with Fermi data? Maybe that would be helpful:
https://fermi.gsfc.nasa.gov/ssc/data/analysis/video_tutorials/#pulsar

Like he mentioned in the other issues, pulsar people generally don't use the Fermitools to do their analysis, and the pulsar tools have been deprecated or removed from the Fermitools.  We can only provide limited  (at best) help with non-Fermitools analysis.

**Comment by TheCriticalSpan** [comment]
@donhorner Can't believe I hadn't run into those videos yet, will definitely get around to watching them soon. I guess I will also take a look at non-Fermitool pulsar analysis as an alternative. Thanks for the help!

**Comment by TheCriticalSpan** [comment]
@donhorner Sorry for reopening the issue but after taking a look at the videos I'm still in the same position. The data analysis itself isn't what I don't get, I'm just not clear how to select phase cuts through the config file using fermipy. I know the phasemin and phasemax arguments are still supported because the code reads them fine, the problem seems to be with how I'm feeding the code the event file with a phase column. All the spectral analsysis once I have successfully made the phase cut I know I can do. Am I just supposed to set evfile in the config file to the phased ft1 file or is there somewhere else I should be inputting it?

**Comment by donhorner** [comment]
Unfortunately, no one currently at the Science Support Center works with pulsars, and Fermipy is a community driven package, so what help we can offer is limited.  Have you looked at the Fermipy documentation for [phased analysis](https://fermipy.readthedocs.io/en/latest/advanced/phased.html)?  You might also want to check out this pulsar analysis [Jupyter notebook ](https://confluence.slac.stanford.edu/download/attachments/382927547/Pulsar_Analysis_with_FermiPy.ipynb?version=1&modificationDate=1685993311000&api=v2) given by one of the speakers at this year's Fermi [Summer School](https://confluence.slac.stanford.edu/display/LSP/Fermi+Summer+School+2023).

**Comment by TheCriticalSpan** [comment]
@donhorner In the end I was able to extract specific phase cuts by manually running gtselect form the terminal including phasemin and phasemax arguments, instead of letting the fermipy setup process do it automatically. Still don't quite know why fermipy wasn't working but at least I got it! Sorry about reopening the issue, hopefully it wasn't too much of a bother
