### ISSUE TITLE
Error when computing light curve

### ISSUE THREAD

**Issue by TheCriticalSpan** [fermi-lat/Fermitools-conda#151]
Hey everyone!
I'm trying to make a light curve for a gamma ray binary but no matter how I set up my bins I always get a type error saying "Object of type int64 is not JSON serializable." It's strange because I only get this error massage at the very end after the analysis has been performed for all bins already and relevant lightcurve folders have been generated in the working directory. I know the analysis is in fact occurring, as I do get bin-by-bin test statistic values for my sources (as well as the code taking a while to run), it's really just the end that messes it up. Does anyone know how to fix this?

**Comment by donhorner** [comment]
What are you using to do this analysis? I think you might be using [Fermipy](https://github.com/fermiPy) which is a community driven project and not supported by the FSSC.  Looking at their issue tracker, this seems to report a similar error to what you see: https://github.com/fermiPy/fermipy/issues/496

**Comment by TheCriticalSpan** [comment]
@donhorner Oh yeah I am using Fermipy. Sorry, I'm fairly new to LAT data analysis and assumed it was the standard so didn't mention it. I will definitely try the solition from the issue you linked and see if it works, thanks!
