### ISSUE TITLE
Query on using EBL model for EBL correction

### ISSUE THREAD

**Issue by sushmitaagarwal** [fermi-lat/Fermitools-conda#155]
I want to evaluate the level of EBL absorption in a LAT spectrum. I came across [this girhub repository](https://github.com/fermi-lat/celestialSources/blob/master/eblAtten/data/README_EBLmodels.txt) which provided a hint that some package is available for using different model (e.g. Franceschini 2008, Stecker et al 2006) for EBL correction. I cannot figure out a way to use these models in the ExpCutoff fitting. I also came across issue number #57  which hinted at a possible way to measure the level of absorption for different models. 
How can I include different EBL models for cutoff correction?
Please suggest

**Comment by nmirabal** [comment]
The XML format for including the EBL in the ExpCutoff fitting is as follows. You can see the differences in the "spectrum type" line and the EBL lines that follow the ExpCutoff definition. There you have to adjust redshift, tau_norm to your source and value in ebl_model refers to the models described in https://github.com/fermi-lat/celestialSources/blob/master/eblAtten/data/README_EBLmodels.txt
 
Finally, make sure that RA and Dec in skydirfunction are correct for your source position

  <source name="Source1" ROI_Center_Distance="0.08" type="PointSource">
  <spectrum type="EblAtten::ExpCutoff" normPar="Prefactor">
<parameter free="1" max="100000.0" min="0.01" name="Prefactor" scale="1e-09" value="50"/>
<parameter free="1" max="-1.0" min="-5." name="Index" scale="1.0" value="-2.1"/>
<parameter free="0" max="2000.0" min="30.0" name="Scale" scale="1.0" value="100.0"/>
<parameter free="1" max="300.0" min="1.0" name="Ebreak" scale="1.0" value="10.0"/>
<parameter free="1" max="300.0" min="0.1" name="P1" scale="1000.0" value="100."/>
<parameter free="0" max="1.0" min="-1.0" name="P2" scale="1.0" value="0"/>
<parameter free="0" max="1.0" min="-1.0" name="P3" scale="1.0" value="0"/>
         <parameter free="0" max="2000" min="30" name="Scale" scale="1" value="100" />
       <parameter free="0" max="10" min="0" name="tau_norm" scale="1.0" value="1."/>
       <parameter free="0" max="10" min="0" name="redshift" scale="1.0" value="0.896"/>
       <parameter free="0" max="8" min="0" name="ebl_model" scale="1.0" value="3"/>
  </spectrum>
  <spatialModel type="SkyDirFunction">
   <parameter free="0" name="RA" max="360.0" min="-360.0" scale="1.0" value="184.0415"/>
   <parameter free="0" name="DEC" max="90.0" min="-90.0" scale="1.0" value="-6.7887"/>
  </spatialModel>

**Comment by nmirabal** [comment]
Right click to download XML file
https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/expebl.xml

**Comment by nmirabal** [comment]
That's the optical depth for the EBL model. You can read more about that in the following link for instance
https://arxiv.org/pdf/1705.10256v1.pdf
