### ISSUE TITLE
Pin version of libgcc-ng

### ISSUE THREAD

**Issue by giacomov** [fermi-lat/Fermitools-conda#16]
It looks like the package libgcc-ng is currently not from conda-forge:

```
> conda create --name fermi_st -c fermi -c conda-forge fermitools

....
    lapack:                             3.6.1-1                       conda-forge
    libffi:                             3.2.1-hfc679d8_5              conda-forge
    libgcc-ng:                          8.2.0-hdf63c60_1                         
    libgfortran:                        3.0.0-1                       conda-forge
    libgfortran-ng:                     7.2.0-hdf63c60_3              conda-forge                      
....
```

There is a version in conda forge, but it's older (it's 7.2.0). So now the fermitools (1.0.0) are built against 8.2.0 which is from the default channels, which means that they might be incompatible with other software built against `conda-forge` packages.

**Comment by jasercion** [comment]
I'll get this updated.

**Comment by jasercion** [comment]
This is something I'd like to hold off on until we finish our C++11 updates.  Once that's done we'll be pulling compilers and associated libraries from Conda (in the same way conda-forge is doing post the January 2019 gcc7 update).

Once we are doing that there should no longer be a need to pin libgcc.

**Comment by jasercion** [comment]
This has been superseded by recipe updates.  Closing issue.
