### ISSUE TITLE
Input xml file not parsed succesfully

### ISSUE THREAD

**Issue by PascualUCM** [fermi-lat/Fermitools-conda#170]
Good morning.

I'm trying to perform an analysis with fermitools, buy got this issue while generating the analysis object.
![error](https://github.com/user-attachments/assets/72c0aac8-eb01-41d7-b67a-a7ac0d16703f)

I first reproduced the jupyter notebook in [FermiSummerSchool](https://github.com/FermiSummerSchool/fermi-summer-school/tree/master/Likelihood_Analysis). No error was found here.

After that, I tried to analyse Omega Centauri region instead of 3C279. I changed coordinates and energy intervals only. I reached the analysis object section, but needed an xml model. No matter what file I try, all of them rise the same error.

I've tried to make it using the recommendations described [here](https://github.com/physicsranger/make4FGLxml) and named it my_model.xml. 
`!make4FGLxml /home/vpascual/anaconda3/envs/fermipy/lib/python3.9/site-packages/fermipy/data/catalogs/gll_psc_v35.fit --event_file ./data/L241207120647E59F266C69_PH00.fits`

Didn't work, so I tried to use the same 3C279.xml just to ensure it wasn't a format problem, but didn't work either. Neither with an empty xml file. I also checked that if I intentionally put a format error in the xml (e.g. didn't close with </>), I get a different issue, meaning these three xml files have none of those errors.

I can't understand why it worked in the SummerSchool notebook but not in a copy of it. 
I'm using version 3.9.19 of python, 2.2.0 of fermitools. I leave a [zip](https://drive.google.com/file/d/1ZA5IKdHTnL8zJY4aTSByTdsx0MFjMtnk/view?usp=sharing) with the jupyter notebook, all of xml models I've used and the event file to create my_model.xml.

Thanks for your help.

**Comment by nmirabal** [comment]
Jupyter issue. It works after closing and restarting the notebook.
