### ISSUE TITLE
Can't activate fermi environment

### ISSUE THREAD

**Issue by physicsranger** [fermi-lat/Fermitools-conda#18]
I have installed anaconda for python2.7 (version 4.5.11) and, as far as code tells me, successfully installed the fermitools ("conda create -n fermi -c conda-forge -c fermi fermitools" does not report any errors). 

I am using .tcsh, and I have sourced <pathtoconda>/etc/profile.d/conda.csh.

When I type conda activate fermi in a terminal window I get the error ":] Event not found." 

When I open a navigator window with anaconda-navigator and try to launch the environment nothing happens and this error is output to the terminal "Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: Error spawning command line “dbus-launch --autolaunch=dd6db46b58114a5f81d75e2f45c766f8 --binary-syntax --close-stderr”: Child process exited with code 1"

Any ideas?

**Comment by physicsranger** [comment]
Addendum:  I just tried this with the install on my laptop (ubuntu vs. centOS 7).  I could activate the fermi environment fine, but conda told me there was a newer version of conda available (I don't know what my previous version was) so I updated, and now I see the same behavior.

**Comment by jasercion** [comment]
@physicsranger I'll see if I can replicate this issue on one of our machines.  This consistently happens with the latest version of conda?  

Were you ever able to activate the environment in either the bash or tcsh shells?

**Comment by physicsranger** [comment]
Hi @jasercion.  With the latest conda (v4.5.11 I believe) this happened on two computers, using csh and tcsh.  When I downgraded to v4.4.0 I was able to activate the environment in both.  I did not try the bash shell.

**Comment by physicsranger** [comment]
Sorry, didn't mean to close it...clicked the wrong button

**Comment by physicsranger** [comment]
Yes.
set prompt = "%S[\!]%s %U`whoami`%u:"

**Comment by jasercion** [comment]
Ok.  Try commenting that out of your .cshrc, re-sourcing it, then activating the environment.

**Comment by jasercion** [comment]
If that worked, try putting a backslash before the `]`.  Let me know if that works as well.

**Comment by physicsranger** [comment]
Commenting that out and re-upgrading to conda 4.5.11, I was able to
activate the fermi environment.  I checked and remodified the prompt, same
issue as before.  I then did as you asked and put a backslash before the ]
and now I was able to activate the environment and my custom prompt was
still there.

**Comment by jasercion** [comment]
Awesome.  This is a bug in the way conda parses the prompt variable when running the cshell activation script.  I've opened an issue with conda (https://github.com/conda/conda/issues/8032). 

For now you will likely need to leave that extra backslash in there (until Conda fixes the parsing).  Let us know if this crops up again!

**Comment by jasercion** [comment]
Closing issue.   Please reopen if this persists.
