### ISSUE TITLE
Tools depend on older version of openssl library

### ISSUE THREAD

**Issue by joeastro** [fermi-lat/Fermitools-conda#20]

**Comment by joeastro** [comment]
This issue can arise when the user installs conda packages to enable using the tools within an iPython notebook. In particular, the module nb_conda depends on openssl v.1.1.1. However, at least a couple tools (gtltcube and gtexpmap2) have openssl v.1.0.0 as a dependency. The resulting error message is:

`time -p gtltcube evfile="" evtable="EVENTS" scfile=SC.fits sctable="SC_DATA" outfile=ltCube_out.fits dcostheta=0.025 binsz=1.0 phibins=0 tmin=554255940.0 tmax=554860800.0 file_version="1" zmin=0.0 zmax=105.0 chatter=2 clobber=yes debug=no gui=no mode="ql"
dyld: Library not loaded: @rpath/libssl.1.0.0.dylib
  Referenced from: /Users/jeggen/anaconda/envs/fermi/lib/root/libNet.5.so
  Reason: image not found`

I can get around this by simply creating a symlink pointing to the new openssl library, but at the location that the tools expect:

`ln -s ~/anaconda/envs/fermi/lib/libssl.1.1.dylib ~/anaconda/envs/fermi/lib/libssl.1.0.0.dylib`

**Comment by jasercion** [comment]
@joeastro Could you check if this is still an issue in the Patch release and close out the issue if it is solved?

**Comment by joeastro** [comment]
Sure, I'll do a clean install and check it early next week (circumstances allowing).

**Comment by jasercion** [comment]
This is something we won't be able to fix until we move to Root6.  The reason we are pulling this older openssl library is because the version of Root5 we are using depends on it.  @donhorner I think we should remove this from the next feature release and group it with Root6 updates for the subsequent release.

**Comment by gudlaugu** [comment]
Doing the symbolic link did not work for my student who installed fermitools on OS X.  There is a symbol missing in the new library _SSL_library_init.  Is there a workaround for this?

**Comment by donhorner** [comment]
We don't have anything right now, but we're looking into it again since we'll need to make sure this works for the Fermi Summer School at the end of May.

**Comment by jasercion** [comment]
@joeastro would you mind checking this in the Python3 release and letting me know if this is still an issue?

**Comment by joeastro** [comment]
Happy to report that this issue is no longer present in the latest release of the tools.
