### ISSUE TITLE
Do the conda-activated fermitools work on a computer-cluster?

### ISSUE THREAD

**Issue by fengli9096** [fermi-lat/Fermitools-conda#22]
I tried to setup the fermitools on a computer-cluster, it seems dose not work well.  Some of the fermitools dosen't run on the computer-cluster, this may due to the environments.

**Comment by Areustle** [comment]
Hello @fengli9096,

Currently we do not support or test the efficacy of the conda activated fermi tools on computer clusters of any sort. Do you have more information about the exact type of analysis you want to perform? And information about the cluster you're using?

**Comment by Areustle** [comment]
Closing as no progress in a month.
