### ISSUE TITLE
Warning on fitsio header

### ISSUE THREAD

**Issue by landriu** [fermi-lat/Fermitools-conda#24]
Hi,

  after having activated fermitools environment, we get the following warning
when calling a tool on our environment though all dependencies on cfitsio have been 
avoided: 
(/dsm/saplxglast/glast/fermitools/1.0.0) 
[landriu@sappcb34] ~ > gtlike
WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).
Statistic to use (BINNED|UNBINNED) [UNBINNED] ^C
.../...

We have:
(/dsm/saplxglast/glast/fermitools/1.0.0) 
[landriu@sappcb34] ~ > env | grep INC
(/dsm/saplxglast/glast/fermitools/1.0.0) 
[landriu@sappcb34] ~ > env | grep FITS
(/dsm/saplxglast/glast/fermitools/1.0.0) 
[landriu@sappcb34] ~ > env | grep fitsio
(/dsm/saplxglast/glast/fermitools/1.0.0) 
[landriu@sappcb34] ~ >
.../...

   as installed distribution shows as waited for : 
 
(/dsm/saplxglast/glast/fermitools/1.0.0) 
[landriu@sappcb34] ~ > ldd /dsm/saplxglast/glast/fermitools/1.0.0/bin/fermitools/gtlike | grep cfitsio
	libcfitsio.so.5 => /dsm/saplxglast/glast/fermitools/1.0.0/bin/fermitools/../../lib/libcfitsio.so.5 (0x00007f923946c000)

The cfitsio library installed is : 
[landriu@sappcb34] ~ > ls /dsm/saplxglast/glast/fermitools/1.0.0/lib/*fitsio*
/dsm/saplxglast/glast/fermitools/1.0.0/lib/libcfitsio.so
/dsm/saplxglast/glast/fermitools/1.0.0/lib/libcfitsio.so.5
/dsm/saplxglast/glast/fermitools/1.0.0/lib/libcfitsio.so.5.3.41

and header contains : 
(/dsm/saplxglast/glast/fermitools/1.0.0) 
[landriu@sappcb34] ~ > grep VERSION /dsm/saplxglast/glast/fermitools/1.0.0/include/*h | grep FITS
/dsm/saplxglast/glast/fermitools/1.0.0/include/fitsio.h:#define CFITSIO_VERSION 3.41
(/dsm/saplxglast/glast/fermitools/1.0.0) 

  Do you see  where could header VERSION 3.43 come from in this warning ?

Thanks

**Comment by donhorner** [comment]
Sorry no one got back to you sooner, but this warning occurs because astropy uses a different version of CFITSIO than the version that the FSSC builds the conda binaries against. It shouldn't cause any issues with analysis.  

We're looking into ways to handle it in a future release.  In the meantime, we've added a note on the [Troubleshooting page](https://github.com/fermi-lat/Fermitools-conda/wiki/Troubleshooting).
