### ISSUE TITLE
Tool gtltcube no longer works without an input events file

### ISSUE THREAD

**Issue by joeastro** [fermi-lat/Fermitools-conda#27]
It used to be possible to run this tool without an input events file, which was useful for making exposure maps for future times. This behaviour is actually necessary for the mission planning software, since part of that routine creates all-sky exposure maps for the week being planned.

I believe this ability was present during the first one or two conda releases, and I'm certain it was in the last release before we switched to conda.

**Comment by jasercion** [comment]
Would you mind reopening this in https://github.com/fermi-lat/Likelihood/issues?  Also, please include the exact command that is being run (if you have that handy.  

Thanks!

**Comment by joeastro** [comment]
Sure, I'll re-post over there now.
