### ISSUE TITLE
Compiling code in the conda environment with ROOTCINT

### ISSUE THREAD

**Issue by phbruel** [fermi-lat/Fermitools-conda#31]
I'm trying to compile some code (my TVista package, available in cvs: users/bruel/TVista) in the conda environment on my laptop (fedora 27).
I used to compile it on my laptop years ago with an old version of the ScienceTools when I had an old gcc version. When upgrading the fedora version, I couldn't compile it. So I ended up using this code at SLAC.

Up to now, I've compiled it at SLAC with ScienceTools (currently ST-11-07-00) thanks to a Makefile that Eric Charles put together for me. One can see my working directory at SLAC: /nfs/farm/g/glast/u/bruel/users/bruel/TVista.

Back to my laptop. I was hoping that using the FermiTools within the conda environment would allow me to compile my code. But it didn't. When switching to the conda environment, the compilation failed.

I've installed FermiTools 1.0.1 with:
conda update -c conda-forge/label/cf201901 -c fermi fermitools

After fixing the INCLUDE paths, the compilation failed when ROOTCINT tries to build the dictionary:
Error: Invalid type 'constexpr' in declaration of 'double pi' /home/bruel/.conda/envs/fermi/include/CLHEP/Units/SystemOfUnits.h:56:

Joe suggested to add --std=c++11 but it doesn't help. The reason is that I have gcc version 7.3.1.

He then suggested to install gcc=4.8.5 via:
conda install -c conda-forge/label/cf201901 gcc=4.8.5
But it didn't fix the compilation problem. The reason is that CINT does not support any C++11 features at all.

He then suggested to install ROOT6 via:
conda install -c conda-forge root
The installation failed:
Solving environment: failedUnsatisfiableError: The following specifications were found to be in conflict:
 - root -> gsl[version='>=2.4,<2.5.0a0']
 - root -> root5==9999
 - root5 -> gsl=2.2
Use "conda info <package>" to see the dependencies for each package.

He then suggested to open an issue. Here it is!

**Comment by jasercion** [comment]
@phbruel Did you ever find a solution to this or is this still an ongoing issue?

**Comment by phbruel** [comment]
WIth Fermitools 1.4.0 or 2.0.0 and ROOT 6, I can compile my code w/o problem. Thanks.
