### ISSUE TITLE
Problem using binnedAnalysis() from fermitools-1.0.5

### ISSUE THREAD

**Issue by landriu** [fermi-lat/Fermitools-conda#35]
Hello,

      after fermitools-1.0.5 installation I got the following
  problem with binnedAnalysis :

(/dsm/saplxglast/glast/fermitools/1.0.5-fermipy)
[landriu@sappcfermi] ~/dev/fermitools-1.0.5 > python
Python 2.7.14 | packaged by conda-forge | (default, Oct  5 2017, 14:19:56)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from BinnedAnalysis import binnedAnalysis

WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).

>>> like = binnedAnalysis( irfs="CALDB", expcube="ltCube_105.fits",srcmdl="srcModel_1_E4.xml-initial",optimizer="Minuit", cmap="srcMap_1_E4.fits", bexpmap="binned_exposure_E4.fits", wmap="/dsm/saplxglast/glast/data/testOneDay/Weights_GP_Source_uw30_P7REPV15.fits",delete_local_fixed=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/dsm/saplxglast/glast/fermitools/1.0.5-fermipy/lib/python2.7/site-packages/fermitools/BinnedAnalysis.py", line 329, in binnedAnalysis
    like.tol = pargroup.getDouble('ftol')
AttributeError: 'tuple' object has no attribute 'tol'
>>
(/dsm/saplxglast/glast/fermitools/1.0.5-fermipy)
[landriu@sappcfermi] ~/dev/fermitools-1.0.5 >

  Can you tell me why I got this error ?

 Thank you for your help.

 Cheers,

   David Landriu

PS:   I may have to add that I could not use the "conda install" or "conda create"
 commands, to have a working version of fermitools-1.0.5 but copied a previous installation and launched "conda update --all " :

  [landriu@sappcfermi] ~ > conda update --all --prefix=/dsm/saplxglast/glast/fermitools/1.0.5-fermipy
  Fetching package metadata ...............
  Solving package specifications: .

  Package plan for installation in environment /dsm/saplxglast/glast/fermitools/1.0.5-fermipy:

  The following NEW packages will be INSTALLED:

      configparser:       3.7.3-py27_1                  conda-forge
      contextlib2:        0.5.5-py_2                    conda-forge
      importlib_metadata: 0.17-py27_1                   conda-forge
      intel-openmp:       2019.4-243
      libblas:            3.8.0-10_mkl                  conda-forge
      libcblas:           3.8.0-10_mkl                  conda-forge
      liblapack:          3.8.0-10_mkl                  conda-forge
      mkl:                2019.4-243
      packaging:          19.0-py_0                     conda-forge
      wcwidth:            0.1.7-py_1                    conda-forge
      zipp:               0.5.1-py_0                    conda-forge

  The following packages will be UPDATED:

      ca-certificates:    2018.11.29-ha4d7672_0         conda-forge --> 2019.3.9-hecc5488_0       conda-forge
      certifi:            2018.11.29-py27_1000          conda-forge --> 2019.3.9-py27_0           conda-forge
      fastcache:          1.0.2-py27h14c3975_1001       conda-forge --> 1.1.0-py27h516909a_0      conda-forge
      fermipy:            0.17.3-py27_1000              conda-forge --> 0.17.4-py27_0             conda-forge
      fermitools:         1.0.1-py27h39e3cac_0          fermi       --> 1.0.5-py27h39e3cac_0      fermi
      fermitools-data:    0.13-0                        fermi       --> 0.17-0                    fermi
      fftw:               3.3.8-h9ac9557_1003           conda-forge --> 3.3.8-nompi_h7f3a6c3_1105 conda-forge
      gettext:            0.19.8.1-h9745a5d_1001        conda-forge --> 0.19.8.1-hc5be6a0_1002    conda-forge
      healpy:             1.12.8-py27h80923ca_1000      conda-forge --> 1.12.9-py27h313ec66_0     conda-forge
      libffi:             3.2.1-hf484d3e_1005           conda-forge --> 3.2.1-he1b5a44_1006       conda-forge
      libgcc-ng:          7.3.0-hdf63c60_0              conda-forge --> 8.2.0-hdf63c60_1
      libgfortran-ng:     7.2.0-hdf63c60_3              conda-forge --> 7.3.0-hdf63c60_0
      libiconv:           1.15-h14c3975_1004            conda-forge --> 1.15-h516909a_1005        conda-forge
      libstdcxx-ng:       7.3.0-hdf63c60_0              conda-forge --> 8.2.0-hdf63c60_1
      mpfr:               4.0.1-ha14ba45_1000           conda-forge --> 4.0.2-ha14ba45_0          conda-forge
      numpy:              1.13.3-py27_blas_openblas_200 conda-forge [blas_openblas] --> 1.16.4-py27h95a1406_0     conda-forge
      pip:                19.0.3-py27_0                 conda-forge --> 19.1-py27_0               conda-forge
      pluggy:             0.9.0-py_0                    conda-forge --> 0.12.0-py_0               conda-forge
      pyparsing:          2.3.1-py_0                    conda-forge --> 2.4.0-py_0                conda-forge
      pytest:             4.3.0-py27_0                  conda-forge --> 4.6.2-py27_0              conda-forge
      pytz:               2018.9-py_0                   conda-forge --> 2019.1-py_0               conda-forge
      pyyaml:             3.13-py27h14c3975_1001        conda-forge --> 5.1-py27h14c3975_0        conda-forge
      scandir:            1.9.0-py27h14c3975_1000       conda-forge --> 1.10.0-py27h14c3975_0     conda-forge
      scipy:              0.19.1-py27_blas_openblas_202 conda-forge [blas_openblas] --> 1.2.1-py27h09a28d5_1      conda-forge
      setuptools:         40.8.0-py27_0                 conda-forge --> 41.0.1-py27_0             conda-forge
      subprocess32:       3.5.3-py27h14c3975_0          conda-forge --> 3.5.4-py27h516909a_0      conda-forge
      sympy:              1.3-py27_1000                 conda-forge --> 1.4-py27_0                conda-forge
      wheel:              0.33.1-py27_0                 conda-forge --> 0.33.4-py27_0             conda-forge
      xorg-libice:        1.0.9-h14c3975_1004           conda-forge --> 1.0.9-h516909a_1004       conda-forge
      xorg-libsm:         1.2.3-h4937e3b_1000           conda-forge --> 1.2.3-h84519dc_1000       conda-forge
      xorg-libxdmcp:      1.1.2-h14c3975_1007           conda-forge --> 1.1.3-h516909a_0          conda-forge
      xorg-libxext:       1.3.3-h14c3975_1004           conda-forge --> 1.3.4-h516909a_0          conda-forge
      xorg-libxrender:    0.9.10-h14c3975_1002          conda-forge --> 0.9.10-h516909a_1002      conda-forge

**Comment by nmirabal** [comment]
To try to track the source, can you try running 

1) without wmap and delete_local_fixed=True
2) just without delete_local_fixed=True

Let us know if you get the same error

**Comment by landriu** [comment]
Hi,

 I did the call without these options and got same message : 

[landriu@sappcfermi] ~/dev/fermitools-1.0.5 > python
Python 2.7.14 | packaged by conda-forge | (default, Oct  5 2017, 14:19:56) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from BinnedAnalysis import binnedAnalysis

WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).

>>> like = binnedAnalysis( irfs="CALDB",expcube="ltCube_105.fits",srcmdl="srcModel_1_E4.xml-initial",optimizer="Minuit", cmap="srcMap_1_E4.fits", bexpmap="binned_exposure_E4.fits")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/dsm/saplxglast/glast/fermitools/1.0.5-fermipy/lib/python2.7/site-packages/fermitools/BinnedAnalysis.py", line 329, in binnedAnalysis
    like.tol = pargroup.getDouble('ftol')
AttributeError: 'tuple' object has no attribute 'tol'
>>>

**Comment by nmirabal** [comment]
Can you try this format?
obs = BinnedObs(srcMaps='file_name',binnedExpMap='file_name',
expCube='file_name',irfs='CALDB')
like = BinnedAnalysis(obs,'XML_file_name',optimizer='Minuit')

**Comment by landriu** [comment]
________________________________
________________________________
________________________________
________________________________
Hi  Nestor,

  I did :


(/dsm/saplxglast/glast/fermitools/1.0.5-fermipy)
[landriu@sappcfermi] ~/dev/fermitools-1.0.5 > python
Python 2.7.14 | packaged by conda-forge | (default, Oct  5 2017, 14:19:56)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from BinnedAnalysis import binnedAnalysis
Warning in <TUnixSystem::SetDisplay>: DISPLAY not set, setting it to hubble.extra.cea.fr:0.0
WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).
>>> from BinnedAnalysis import BinnedObs
>>> obs = BinnedObs(srcMaps='srcMap_1_E4.fits',binnedExpMap='binned_exposure_E4.fits', expCube='ltCube_105.fits',irfs='CALDB')
>>> like = binnedAnalysis(obs,'srcModel_1_E4.xml-initial',optimizer='Minuit')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/dsm/saplxglast/glast/fermitools/1.0.5-fermipy/lib/python2.7/site-packages/fermitools/BinnedAnalysis.py", line 319, in binnedAnalysis
    irfs=irfs, phased_expmap=phased_expmap)
  File "/dsm/saplxglast/glast/fermitools/1.0.5-fermipy/lib/python2.7/site-packages/fermitools/BinnedAnalysis.py", line 66, in __init__
    my_cuts = pyLike.Cuts(srcMaps, "", False, True, True)
  File "/dsm/saplxglast/glast/fermitools/1.0.5-fermipy/lib/python2.7/site-packages/fermitools/pyLikelihood.py", line 2253, in __init__
    this = _pyLikelihood.new_Cuts(*args)
RuntimeError: File not found: none
>>>

Cheers,

  David Landriu

PS: All input files I used exist :

[landriu@sappcfermi] ~/dev/fermitools-1.0.5 > ls
binned_exposure_E4.fits  pycmd.txt         srcModel_1_E4.xml-initial
ltCube_105.fits          srcMap_1_E4.fits  testBinnedObs.txt


De : nmirabal [notifications@github.com]
Envoyé : mardi 11 juin 2019 18:09
À : fermi-lat/Fermitools-conda
Cc : Landriu David; State change
Objet : Re: [fermi-lat/Fermitools-conda] Problem using binnedAnalysis() from fermitools-1.0.5 (#35)


Can you try this format?
obs = BinnedObs(srcMaps='file_name',binnedExpMap='file_name',
expCube='file_name',irfs='CALDB')
like = BinnedAnalysis(obs,'XML_file_name',optimizer='Minuit')

**Comment by nmirabal** [comment]
I reproduced the original error as you posted it, but the latter format should not generate any errors. Can you verify that the files are correctly produced?. Can you rename the files by removing the underscore _?. If the error persists, would you mind making your files available for testing?.

**Comment by nmirabal** [comment]
One more thing, calls are case-sensitive, start with 
import pyLikelihood
from BinnedAnalysis import * 

Please use BinnedObs and BinnedAnalysis

**Comment by landriu** [comment]
Hi,

  I could launch the test using BinnedAnalysis instead binnedAnalysis without
errors indeed :


(/dsm/saplxglast/glast/fermitools/1.0.5-fermipy)
[landriu@sappcfermi] ~/dev/fermitools-1.0.5 > python
Python 2.7.14 | packaged by conda-forge | (default, Oct  5 2017, 14:19:56)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from BinnedAnalysis import BinnedAnalysis,BinnedObs
Warning in <TUnixSystem::SetDisplay>: DISPLAY not set, setting it to hubble.extra.cea.fr:0.0
WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).
>>> obs = BinnedObs(srcMaps='srcMap_1_E4.fits',binnedExpMap='binned_exposure_E4.fits', expCube='ltCube_105.fits',irfs='CALDB')
>>> like = BinnedAnalysis(obs,'srcModel_1_E4.xml-initial',optimizer='Minuit')
>>>
(/dsm/saplxglast/glast/fermitools/1.0.5-fermipy)
[landriu@sappcfermi] ~/dev/fermitools-1.0.5 >
…/…

  I could also try, and got no error message  :

[landriu@sappcfermi] ~/dev/fermitools-1.0.5 > python
Python 2.7.14 | packaged by conda-forge | (default, Oct  5 2017, 14:19:56)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyLikelihood
Warning in <TUnixSystem::SetDisplay>: DISPLAY not set, setting it to hubble.extra.cea.fr:0.0
WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).
>>> from BinnedAnalysis import *
>>> obs = BinnedObs(srcMaps='srcMap_1_E4.fits',binnedExpMap='binned_exposure_E4.fits', expCube='ltCube_105.fits',irfs='CALDB')
>>>
>>> like = BinnedAnalysis(obs,'srcModel_1_E4.xml-initial',optimizer='Minuit')
>>>



   David Landriu


________________________________
De : nmirabal [notifications@github.com]
Envoyé : mercredi 12 juin 2019 18:39
À : fermi-lat/Fermitools-conda
Cc : Landriu David; State change
Objet : Re: [fermi-lat/Fermitools-conda] Problem using binnedAnalysis() from fermitools-1.0.5 (#35)


One more thing, calls are case-sensitive, start with
import pyLikelihood
from BinnedAnalysis import *

Please use BinnedObs and BinnedAnalysis

**Comment by jasercion** [comment]
Reopening issue.

**Comment by jasercion** [comment]
Apparently the fix for the BinnedAnalysis/pyLikelihood interface is directly tied to a number of changes that were made to introduce the new energy dispersion calculation into the new Fermitools.  This unfortunately means we won't be able to release this fix until we are clear to releasing the next major feature release of the tools.  

Currently the candidate release with those changes is in testing.  Hopefully we will finish validating the changes soon and can shortly thereafter release the build to the community.

**Comment by jasercion** [comment]
@nmirabal Would you mind checking if this is still occurring in the Fermitools 2.0.0 release of the tools?

**Comment by landriu** [comment]
Hello Jon,

    I tried on my side and it works using fermi-2.0.0 :

(fermi-2.0.0)
[landriu@sappcfermi] ~/dev/testBinnedAnalysis/testFermi-2.0.0 > python
*Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> from BinnedAnalysis import binnedAnalysis
>>>
>>> like = binnedAnalysis( irfs="CALDB", expcube="ltCube_105.fits", srcmdl="srcModel_1_E1.xml-initial",optimizer="Minuit", cmap="srcMap_1_E1.fits", bexpmap="binned_exposure_E1.fits", wmap="Weights_GP_Source_uw30_P7REPV15.fits",delete_local_fixed=True)
Generating SourceMap for PSRJ0534+2200 11.....................!
>>> like.sourceNames
<bound method AnalysisBase.sourceNames of Source maps: srcMap_1_E1.fits
Exposure cube: ltCube_105.fits
Exposure map: binned_exposure_E1.fits
IRFs: CALDB
Source model file: srcModel_1_E1.xml-initial
Optimizer: Minuit>
>>> like.sourceNames()
('EXTIC443', 'LAT0004', 'LAT0005', 'PSRJ0534+2200', 'SunIC_v2', 'eg_v02', 'gal_v02')
>>>
(fermi-2.0.0)

 Cheers,

   David


________________________________
De : jasercion [notifications@github.com]
Envoyé : mercredi 21 octobre 2020 20:29
À : fermi-lat/Fermitools-conda
Cc : Landriu David; State change
Objet : Re: [fermi-lat/Fermitools-conda] Problem using binnedAnalysis() from fermitools-1.0.5 (#35)


@nmirabal<https://github.com/nmirabal> Would you mind checking if this is still occurring in the Fermitools 2.0.0 release of the tools?
