### ISSUE TITLE
QGTKstyle could not resolve GTK

### ISSUE THREAD

**Issue by Sanjuphysics12** [fermi-lat/Fermitools-conda#36]
"QGtkStyle could not resolve GTK. Make sure you have installed the proper libraries." Even after updating and reinstalling the library, I am getting this error again and again. How can I resolve this ?

**Comment by jasercion** [comment]
@Sanjuphysics12 What tool are you attempting to launch that is throwing this error?  QGtkStyle is a library used by the system to render GUI interfaces, so it is likely that this isn't the direct source of the error but rather a side effect of an earlier failure in launching a tool.  

What OS are you using?

**Comment by Sanjuphysics12** [comment]
@jasercion ubuntu 16.04.

**Comment by jasercion** [comment]
@Sanjuphysics12 What tool are you attempting to launch?

**Comment by Sanjuphysics12** [comment]
@jasercion  gtlike

**Comment by jasercion** [comment]
Hi @Sanjuphysics12, would you mind updating to Fermitools 2.0.0 and seeing if this is still occurring?  A number of changes have been implemented between the previous release and this one so the problem may be resolved.
