### ISSUE TITLE
ST_Version error

### ISSUE THREAD

**Issue by L61** [fermi-lat/Fermitools-conda#37]
ST_Version script fails to produce a version number and crashes when running GTAnalysis from fermipy

Dump:

AttributeError                            Traceback (most recent call last)
<ipython-input-6-123b6f2911ac> in <module>()
----> 1 gta = GTAnalysis('config.yaml')
      2 matplotlib.interactive(True)
      3 gta.setup()

/home/username/anaconda3/envs/fermi/lib/python2.7/site-packages/fermipy/gtanalysis.pyc in __init__(self, config, roi, **kwargs)
    300                         "fermipy version {} ".
    301                         format(fermipy.__version__) + '\n' +
--> 302                         'ScienceTools version %s', fermipy.get_st_version())
    303         self.print_config(self.logger, loglevel=logging.DEBUG)
    304 

/home/username/anaconda3/envs/fermi/lib/python2.7/site-packages/fermipy/__init__.pyc in get_st_version()
     23     try:
     24         import ST_Version
---> 25         return ST_Version.version()
     26     except ImportError:
     27         return ''

AttributeError: 'module' object has no attribute 'version'

**Comment by jasercion** [comment]
@L61 Would you mind testing this with a development build we have prepared?  I think we may have a fix for this.  I'd suggest creating a new environment and installing it there to run the test.  The test build can be installed with the following command:

`conda install -c conda-forge/label/cf201901 -c fermi -c fermi/label/dev fermitools=1.0.8`

**Comment by L61** [comment]
Unfortunately it keeps throwing the same error.

This is on a new environment, with only fermitools 1.0.8, fermipy and jupyter notebook (+ dependencies) installed

**Comment by jasercion** [comment]
@L61 Thanks for trying that.  

@eacharles Any ideas offhand as to where this could be failing within the ST_Version chain?

**Comment by Fdepalma** [comment]
I temporarily solved this issue downgrading to the version 1.0.2 that it is available on conda

**Comment by jasercion** [comment]
@Fdepalma @L61 I have a test version with a patch on a development label.  Would you both mind verifying that this build solves the problem?  It can be installed with the following command:

`conda install -c conda-forge/label/cf201901 -c fermi -c fermi/label/dev fermitools=1.0.9`

I suggest doing so in a newly created environment specifically for testing purposes.

**Comment by L61** [comment]
@jasercion that seems to work fine (for the moment at least). The program reports "ScienceTools version unknown", but that's not a big deal.

Thank you for the quick fix!

**Comment by Fdepalma** [comment]
@jasercion It seems to work fine for the example I have tested. The fermipy starting output is:
2019-07-01 11:02:00 INFO    GTAnalysis.__init__(): 
--------------------------------------------------------------------------------
fermipy version 0.17.4 
ScienceTools version unknown
