### ISSUE TITLE
AttributeError: 'module' object has no attribute 'new_table'

### ISSUE THREAD

**Issue by Sanjuphysics12** [fermi-lat/Fermitools-conda#42]
NOTE: Band7, with center energy 19.0529425421 GeV, quoting 95% upper limit on flux.
Traceback (most recent call last):
  File "Sed.py", line 95, in <module>
    sed.Plot()
  File "/path/SED/likeSED.py", line 148, in Plot
    plotSED(self,plot)
  File "/path/SED/likeSED.py", line 921, in plotSED
    writeSpecFits(sed,modBins,modelEcent,[x/1000. for x in newminEs],[x/1000. for x in newmaxEs],GeVfluxPts,GeVfluxErrs,newecent,EsqFluxes,EsqFErrors) #write the output to a sed.Fits file
  File "/path/SED/likeSED.py", line 935, in writeSpecFits
    fitTable=pyfits.new_table([modEcentCol,fitCol,btCol])
AttributeError: 'module' object has no attribute 'new_table'

Cannot solve this problem during SED analysis. Kindly help.

**Comment by nmirabal** [comment]
This is a user contributed script and we cannot provide much support for it. Could you run the following analysis thread to see if you encounter the same error?
https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/python_tutorial.html

**Comment by Sanjuphysics12** [comment]
@nmirabal still getting the same error ( I followed all the steps, mentioned in that page). Another thing is that, I chose 'nbins=9' but 7  bins were formed and after plotting the sed the same error I got.
