### ISSUE TITLE
fermitools behaviour sensitive to the linux version

### ISSUE THREAD

**Issue by landriu** [fermi-lat/Fermitools-conda#43]
Hello,

   I have installed fermitools-1.0.10 and when I work on interactive python, I have an import
error on : 
>>> import matplotlib.pyplot as plt
 .../...
 ImportError: /usr/lib64/libgobject-2.0.so.0: undefined symbol: g_date_copy

 If I do "uname -a" on my machine, I get : 

Linux sappcfermi.extra.cea.fr 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

  I do not meet this problem working on another machine with "uname -a" returning : 
Linux sapgaia1.extra.cea.fr 3.10.0-123.4.2.el7.x86_64 #1 SMP Tue Jun 24 13:05:26 CDT 2014 x86_64 x86_64 x86_64 GNU/Linux

 It seems to me that fermitools behaviour is sensitive to the linux version .

Can you have a check on it ?

Thanks in advance.

PS: whole output : 
[gtpiplin@sappcfermi] ~ > python
Python 2.7.14 | packaged by conda-forge | (default, Oct  5 2017, 14:19:56) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
*** Using startup saving python history in ~/.pyhistory *** 

>>> import matplotlib.pyplot as plt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/dsm/saplxglast/glast/fermitools/1.0.10/lib/python2.7/site-packages/matplotlib/pyplot.py", line 116, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/dsm/saplxglast/glast/fermitools/1.0.10/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 60, in pylab_setup
    [backend_name], 0)
  File "/dsm/saplxglast/glast/fermitools/1.0.10/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import (
  File "/dsm/saplxglast/glast/fermitools/1.0.10/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 18, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/dsm/saplxglast/glast/fermitools/1.0.10/lib/python2.7/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/dsm/saplxglast/glast/fermitools/1.0.10/lib/python2.7/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 56, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/dsm/saplxglast/glast/fermitools/1.0.10/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py", line 137, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: /usr/lib64/libgobject-2.0.so.0: undefined symbol: g_date_copy
>>>

**Comment by jasercion** [comment]
I'll look into this.  It looks like the symbol is part of Glib which is a very low level date/time library.  This is a Red Hat machine?

**Comment by jasercion** [comment]
Which version of the OS?

**Comment by landriu** [comment]
I have on the working machine :

(/dsm/saplxglast/glast/fermitools/1.0.10) landriu@sapgaia1:~$ hostnamectl
   Static hostname: sapgaia1.extra.cea.fr
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 1b519139d44f4215ae4e9279bb0262cd
           Boot ID: 3f815cc27af04272b87c5b889a2da8f8
    Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-123.4.2.el7.x86_64
      Architecture: x86-64

as on the failing one : 
  [landriu@sappcfermi] ~ > hostnamectl
     Static hostname: sappcfermi.extra.cea.fr
           Icon name: computer-desktop
           Chassis: desktop
           Machine ID: bd434e39acbd481baab54df4b4d6eef2
            Boot ID: fabd4dd51ba94cfb834f5e749dc61cce
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-957.21.3.el7.x86_64
      Architecture: x86-64

**Comment by landriu** [comment]
Hi,

  test is now working with beta : fermi-1.3.5 on both machines : 


(fermi-1.3.5) 
[landriu@sappcfermi] ~/dev/testFermi_beta/simple-with-1.3.5 > python
Python 2.7.15 | packaged by conda-forge | (default, Mar  5 2020, 14:56:06) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
*** Using startup saving python history in ~/.pyhistory *** 

>>> import matplotlib.pyplot as plt
>>> 
(fermi-1.3.5) 

   Thanks again,  I close this issue
