### ISSUE TITLE
Python3 roadmap?

### ISSUE THREAD

**Issue by paulray** [fermi-lat/Fermitools-conda#44]
Is there somewhere that describes the plan for Fermitools to migrate to Python3?
Python 2.7 support is disappearing from all of the major packages by 2020 (see https://python3statement.org).  What is the plan for Fermi?

**Comment by donhorner** [comment]
We have a wiki page with a [general roadmap for the  Fermitools](https://github.com/fermi-lat/Fermitools-conda/wiki/Fermitools-Roadmap). It's not every detailed (and needs some updating).  We also have a github project board (which is not public).  We were hoping to get this done for a Q3 release but other things have come up and no one is working full time on the tools anymore, so it will likely take longer than hoped. Right now, we've completed moving the build pipeline to Microsoft Azure and are finishing up making the tools C++11 compatible which will fix a number of issues we've had.  After that, we'll tackle issues with getting [SWIG](http://www.swig.org/) and [SCons](https://scons.org/) (the build system) to use Py3 and any syntax changes. I'm hoping we can get it out before the end of the year.

**Comment by paulray** [comment]
Thanks, that is just what I was looking for!

**Comment by paulray** [comment]
I happened upon this notice that Python 2 will lose all support on January 1, 2020.
https://www.python.org/doc/sunset-python-2/

**Comment by cameronrulten** [comment]
How's the Python 3 transitioning coming along? Any updates?

**Comment by donhorner** [comment]
Unfortunately, it has been slow going, partly because people have had to work on other projects/issues and haven't had as much time on it as anticipated.  The problems right now are mainly that switching to Python 3 in conda requires updating the compilers and a bunch of dependencies (like ROOT) that break the builds.  We're still trying to resolve those issues.

**Comment by cxwx** [comment]
Now, It's time to switch to python3, any new plan?

**Comment by donhorner** [comment]
We're hoping to get a release out soon.  The Python 3 changes have been done, but other issues have cropped up that keep delaying the release.

**Comment by donhorner** [comment]
Fermitools 2.0 which contains the py3 update has been released.  See the [release notes](https://github.com/fermi-lat/Fermitools-conda/wiki/Release-Notes).
