### ISSUE TITLE
wrong parameters asked for by gtmodel with fermitools-1.1.7

### ISSUE THREAD

**Issue by landriu** [fermi-lat/Fermitools-conda#45]
Hello,

 doing tests with developpement  fermitools  version 1.1.7, gtmodel asked for
wrong parameters ptsrc, minbinsz, and wmap when launching : 

source activate $NFS_ZONE/fermitools/1.1.7-orig
(/dsm/saplxglast/glast/fermitools/1.1.7-orig) 
[landriu@sappcfermi] ~/dev/testGtModel > gtmodel srcmaps=srcMap_1_E3.fits bexpmap=binned_exposure_E3.fits expcube=LiveTimeCube_1.fits srcmdl=srcModel_1.xml outfile=srcMap_1_E3.fits_ModelMap irfs=CALDB

WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).

Parameter edisp_bins not found in parameter group gtmodel (at /opt/conda/conda-bld/fermitools_1562873259624/work/hoops/build/centos6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 0 for parameter edisp_bins
Parameter ptsrc not found in parameter group gtmodel (at /opt/conda/conda-bld/fermitools_1562873259624/work/hoops/build/centos6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 1 for parameter ptsrc
Parameter minbinsz not found in parameter group gtmodel (at /opt/conda/conda-bld/fermitools_1562873259624/work/hoops/build/centos6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 0.1 for parameter minbinsz
Parameter edisp_bins not found in parameter group gtmodel (at /opt/conda/conda-bld/fermitools_1562873259624/work/hoops/build/centos6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 0 for parameter edisp_bins
Parameter wmap not found in parameter group gtmodel (at /opt/conda/conda-bld/fermitools_1562873259624/work/hoops/build/centos6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of none for parameter wmap
Exception en point flottant (core dumped)
(/dsm/saplxglast/glast/fermitools/1.1.7-orig) 

 1.1.7-orig being installed with following command : 
conda install -c conda-forge/label/cf201901 -c fermi -c fermi/label/dev fermitools=1.1.7 --prefix=$NFS_ZONE/fermitools/1.1.7-orig

If I set edisp_bins to 0, I get then : 

[landriu@sappcfermi] ~/dev/testGtModel > gtmodel srcmaps=srcMap_1_E3.fits bexpmap=binned_exposure_E3.fits expcube=LiveTimeCube_1.fits srcmdl=srcModel_1.xml outfile=srcMap_1_E3.fits_ModelMap irfs=CALDB edisp_bins=0

WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).

Invalid parameter name in command line assignment: "edisp_bins"
Invalid parameter name in command line assignment: "edisp_bins"
Caught N5hoops12ApeExceptionE at the top level: Cannot open parameter file for gtmodel; Ape exception code 22 (at /opt/conda/conda-bld/fermitools_1562873259624/work/hoops/build/centos6-x86_64-64bit-gcc48/src/hoops_ape.cxx: 435)
(/dsm/saplxglast/glast/fermitools/1.1.7-orig) 

  As it should accept it as an optional parameter, as written in gtmodel.par of the syspfiles .

 May you have a check ? 

Thanks for your help,

Cheers,

  David Landriu

**Comment by donhorner** [comment]
I don't see this issue when I run gtmodel in the dev version.  I think your gtmodel is picking up an old or corrupted par file somewhere.  If you do a `plist gtmodel `, it should tell you where the par file is (probably your home directory).  Try deleting it, and when you run the tool again it will copy the one from syspfiles.

**Comment by donhorner** [comment]
Did you mean to close this issue @landriu?  It looks like you still had a question.

The `/dsm/saplxglast/home/landriu/pfiles/gtmodel.par` file is definitely the "old" one for the release version.  Did you try to delete it?

The `/dsm/saplxglast/glast/fermitools/1.1.7-orig/share/fermitools/syspfiles/gtmodel.par` file is the correct one for the new version.  It does have the `edisp_bins` parameter. 

The other parameters like ptsrc, minbinsz are from gtsrcmaps.  Offhand, it looks like the gtmodel code is calling gtsrcmaps functions internally and not setting them correctly because it's confused by the lack of an edisp_bins parameter.  The code might require more error checking for these situations.

**Comment by landriu** [comment]
Hi Don,
 
 >> Did you mean to close this issue @landriu? It looks like you still had a question.
 Sorry, I just clicked the wrong buyttpn. 

  I removed $HOME/pfiles/gtmodel.par and it did not have any effect on the result, 
and I got the same output : 

[landriu@sappcfermi] ~/dev/testGtModel > plist gtmodel
Parameters for /dsm/saplxglast/home/landriu/pfiles/gtmodel.par
      srcmaps = srcMap_1_E3.fits Source maps (or counts map) file
       srcmdl = srcModel_1.xml   Source model file
      outfile = srcMap_1_E3.fits_ModelMap Output file
         irfs = CALDB            Response functions
      (evtype = INDEF)           Event type selections
      expcube = LiveTimeCube_1.fits Exposure cube
      bexpmap = binned_exposure_E3.fits Binned exposure map
      (convol = yes)             Perform convolution with psf
    (resample = yes)             Resample input counts map for convolution
     (rfactor = 2)               Resampling factor
     (outtype = CMAP)            Output type
     (psfcorr = yes)             Apply psf integral corrections
       (edisp = no)              Apply energy dispersion?
     (chatter = 2)               Output verbosity
     (clobber = yes)             Overwrite existing output files
       (debug = no)              Activate debugging mode
         (gui = no)              GUI mode activated
        (mode = ql)              Mode of automatic parameters
(/dsm/saplxglast/glast/fermitools/1.1.7-orig) 
[landriu@sappcfermi] ~/dev/testGtModel > \rm /dsm/saplxglast/home/landriu/pfiles/gtmodel.par
(/dsm/saplxglast/glast/fermitools/1.1.7-orig) 
[landriu@sappcfermi] ~/dev/testGtModel > which gtmodel
/dsm/saplxglast/glast/fermitools/1.1.7-orig/bin/fermitools/gtmodel
(/dsm/saplxglast/glast/fermitools/1.1.7-orig) 
[landriu@sappcfermi] ~/dev/testGtModel > gtmodel srcmaps=srcMap_1_E3.fits bexpmap=binned_exposure_E3.fits expcube=LiveTimeCube_1.fits srcmdl=srcModel_1.xml outfile=srcMap_1_E3.fits_ModelMap irfs=CALDB

WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).

Parameter edisp_bins not found in parameter group gtmodel (at /opt/conda/conda-bld/fermitools_1562873259624/work/hoops/build/centos6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 0 for parameter edisp_bins
Parameter ptsrc not found in parameter group gtmodel (at /opt/conda/conda-bld/fermitools_1562873259624/work/hoops/build/centos6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 1 for parameter ptsrc
Parameter minbinsz not found in parameter group gtmodel (at /opt/conda/conda-bld/fermitools_1562873259624/work/hoops/build/centos6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 0.1 for parameter minbinsz
Parameter edisp_bins not found in parameter group gtmodel (at /opt/conda/conda-bld/fermitools_1562873259624/work/hoops/build/centos6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 0 for parameter edisp_bins
Parameter wmap not found in parameter group gtmodel (at /opt/conda/conda-bld/fermitools_1562873259624/work/hoops/build/centos6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of none for parameter wmap
Exception en point flottant (core dumped)
(/dsm/saplxglast/glast/fermitools/1.1.7-orig) 
[landriu@sappcfermi] ~/dev/testGtModel > 
(/dsm/saplxglast/glast/fermitools/1.1.7-orig) 
[landriu@sappcfermi] ~/dev/testGtModel > 

  Your explanation may be true, and the hoops system should indeed detect the missing
parameter without going further in the list of gtmodel dependencies I guess ...

Thanks again,
  Cheers,
      David

**Comment by jasercion** [comment]
I believe this is at least tangentially related to https://github.com/fermi-lat/Likelihood/issues/50 and may be fixed in the dev build 1.2.32.  @landriu could you please check to see if you are seeing this failure continue to crop up with this version?  It can be installed with

`conda install -c conda-forge/label/cf201901 -c fermi -c fermi/label/dev fermitools=1.2.32`

**Comment by omersajid9** [comment]
@jasercion The latest version, I think, is 1.2.23. I tried updating it to it but still I am getting the errors similar to landriu:

Parameter ptsrc not found in parameter group gtlike (at /local/data/glitz1/gssctest/miniconda2/envs/build/conda-bld/fermitools_1580999712705/work/hoops/build/redhat6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 1 for parameter ptsrc
Parameter convol not found in parameter group gtlike (at /local/data/glitz1/gssctest/miniconda2/envs/build/conda-bld/fermitools_1580999712705/work/hoops/build/redhat6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 1 for parameter convol
Parameter resample not found in parameter group gtlike (at /local/data/glitz1/gssctest/miniconda2/envs/build/conda-bld/fermitools_1580999712705/work/hoops/build/redhat6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 1 for parameter resample
Parameter rfactor not found in parameter group gtlike (at /local/data/glitz1/gssctest/miniconda2/envs/build/conda-bld/fermitools_1580999712705/work/hoops/build/redhat6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 2 for parameter rfactor
Parameter minbinsz not found in parameter group gtlike (at /local/data/glitz1/gssctest/miniconda2/envs/build/conda-bld/fermitools_1580999712705/work/hoops/build/redhat6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 0.1 for parameter minbinsz

**Comment by donhorner** [comment]
@omersajid9 You can just ignore these warnings for now.  This will be fixed for the next release, which has been delayed for various reasons, but hopefully will be out soon.

**Comment by jasercion** [comment]
@landriu This appears to be fixed in my latest testing of dev/beta version 1.3.4.  Closing issue.
