### ISSUE TITLE
 Minuit HESSE results invalid

### ISSUE THREAD

**Issue by Sanjuphysics12** [fermi-lat/Fermitools-conda#46]
How to resolve the following error: ( I got it during lightcurve generation)

"RuntimeError: Minuit HESSE results invalid"

**Comment by nmirabal** [comment]
You have to provide more details. Please read the FSSC recommendations on Minuit and NewMinuit in the "Run the Likelihood Analysis" at  the following link
https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/python_tutorial.html

**Comment by Sanjuphysics12** [comment]
**Working on range (550368005.000000,550454405.000000)
***Running likelihood analysis***
Info in <Minuit2>: MnHesse: 2nd derivative zero for Parameter  : name = 0_Prefactor
Info in <Minuit2>: MnHesse fails and will return diagonal matrix 
Info in <Minuit2>: CombinedMinimumBuilder: migrad method fails, will try with simplex method first.
Info in <Minuit2>: MnHesse: 2nd derivative zero for Parameter  : name = 0_Prefactor
Info in <Minuit2>: MnHesse fails and will return diagonal matrix 
Info in <Minuit2>: MnHesse: 2nd derivative zero for Parameter  : name = 0_Prefactor
Info in <Minuit2>: MnHesse fails and will return diagonal matrix 
Info in <Minuit2>: CombinedMinimumBuilder: both migrad and method fails also at 2nd attempt.
Info in <Minuit2>: CombinedMinimumBuilder: return simplex Minimum.
Info in <Minuit2>: MnHesse: 2nd derivative zero for Parameter  : name = 0_Prefactor
Info in <Minuit2>: MnHesse fails and will return diagonal matrix ^M
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "LightCurve.py", line 140, in runLikelihood
    like.fit(verbosity=0,covar=True,optObject=likeObj)
  File "/home/skmondal/anaconda3/envs/fermi/lib/python2.7/site-packages/fermitools/AnalysisBase.py", line 77, in fit
    optObject=optObject, numericDerivs=numericDerivs)
  File "/home/skmondal/anaconda3/envs/fermi/lib/python2.7/site-packages/fermitools/AnalysisBase.py", line 122, in _errors
    myOpt.find_min(verbosity, tol, self.tolType)
  File "/home/skmondal/anaconda3/envs/fermi/lib/python2.7/site-packages/fermitools/pyLikelihood.py", line 4289, in find_min
    return _pyLikelihood.NewMinuit_find_min(self, *args)
RuntimeError: Minuit HESSE results invalid
>>> 

@nmirabal, I was following the tutorial and trying to generate lightCurve but when I put lc.runLikelihood(), for the first few time intervals it looks good [ say I have a data for 150 days and I binned for oneday] then for a particular time interval I got such error, which as much as I understand is related to the error matrix and it failed to generate that matrix. 
The one possible solution is to drop this/such time interval(s) and connect the others in order to get a full lightcurve for a certain period but I want to know, is there any other way to solve this issue?

**Comment by nmirabal** [comment]
You might be missing sufficient counts in that particular time bin. You can increase the bin size (> 1 day) or try to estimate an upper limit for that particular bin.
https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/upper_limits.html
