### ISSUE TITLE
edisp_bins parameter missing in fermitools 1.2.0

### ISSUE THREAD

**Issue by landriu** [fermi-lat/Fermitools-conda#47]
Hello,

   I installed the new fermitools using command : 

conda create -c conda-forge/label/cf201901 -c fermi fermitools sympy --prefix=/dsm/saplxglast/glast/fermitools/1.2.0

  and got a workable environment using : source activate $NFS_ZONE/fermitools/1.2.0

I deleted $HOME/pfiles/gtsrcmaps.par as told in Release Notes

I tried to launch manually the command : 

/dsm/saplxglast/glast/fermitools/1.2.0) 
[landriu@sappcfermi] ~/dev/testGtSrcMaps/testTHb > gtsrcmaps scfile=/dsm/fermi/fermifast/glast/runs/tHb/input/ft2_july09_pass8.fits expcube=/dsm/fermi/fermifast/glast/runs/tHb/input/ltcube_july09_pass8.fits cmap=count_cube_1_E5.fits srcmdl=srcModel_1_E5.xml-initial bexpmap=binned_exposure_E5.fits wmap=none outfile=srcMap_1_E5.fits irfs=CALDB ptsrc=no edisp_bins=0 chatter=4

WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).

Invalid parameter name in command line assignment: "edisp_bins"
Invalid parameter name in command line assignment: "edisp_bins"
Caught N5hoops12ApeExceptionE at the top level: Cannot open parameter file for gtsrcmaps; Ape exception code 22 (at /usr/share/miniconda/conda-bld/fermitools_1570047452161/work/hoops/build/debianstretch/sid-x86_64-64bit-gcc48/src/hoops_ape.cxx: 435)
(/dsm/saplxglast/glast/fermitools/1.2.0) 
[landriu@sappcfermi] ~/dev/testGtSrcMaps/testTHb >

..../....

   I did : plist gtsrcmaps | grep edisp_bins
         and it gives back nothing .

  Do you see what is happening here ?

Thanks in advance,

   David

PS: 

(/dsm/saplxglast/glast/fermitools/1.2.0) 
[landriu@sappcfermi] ~/dev/testGtSrcMaps/testTHb > plist gtsrcmaps
Parameters for /dsm/saplxglast/home/landriu/pfiles/gtsrcmaps.par
      (scfile = )                Spacecraft data file
     (sctable = SC_DATA)         Spacecraft data extension
      expcube = /dsm/fermi/fermifast/glast/runs/tH/input/ltCube_105.fits Exposure hypercube file
         cmap = /tmp/tmp-tH386342/count_cube_1_E3.fits Counts map file
       srcmdl = /tmp/tmp-tH386342/srcModel_1_E3.xml-initial Source model file
      bexpmap = /dsm/fermi/fermifast/glast/runs/tH/like/Rois/binned_exposure_E3.fits Binned exposure map
        (wmap = none)            Likelihood weights map
      outfile = /dsm/fermi/fermifast/glast/runs/tH/like/Rois/srcMap_1_E3.fits Source maps output file
         irfs = CALDB            Response functions
      (evtype = INDEF)           Event type selections
      (convol = yes)             Perform convolution with psf
    (resample = yes)             Resample input counts map for convolution
     (rfactor = 2)               Resampling factor
    (minbinsz = 0.1)             Minimum pixel size for rebinning fine maps
       (ptsrc = yes)             Compute point source maps
     (psfcorr = yes)             Apply psf integral corrections
    (emapbnds = yes)             Enforce boundaries of exposure map
     (copyall = no)              Copy all source maps from input counts map file to output
     (chatter = 2)               Output verbosity
     (clobber = yes)             Overwrite existing output files
       (debug = no)              Activate debugging mode
         (gui = no)              GUI mode activated
        (mode = ql)              Mode of automatic parameters
(/dsm/saplxglast/glast/fermitools/1.2.0)

**Comment by donhorner** [comment]
It looks like the correct par files aren't getting installed for all the tools.  I can see that the edisp_bins option is missing in the installed par files in syspfiles for some of the tools even though it's in the versions in [master](https://github.com/fermi-lat/Likelihood/tree/master/pfiles).

@jasercion can you take a look and see why the old par files are getting installed?

**Comment by donhorner** [comment]
I did a complete fresh install of the tools rather than updating an existing environment and the correct par files are now in that environment's syspfiles directory.  So I guess conda isn't overwriting the ones that are already there?

**Comment by donhorner** [comment]
We released version 1.2.1 which should fix this problem. Try updating and see if the problem persists.

**Comment by jasercion** [comment]
Issue should be fixed.  Closing issue.

**Comment by landriu** [comment]
Hello Joe,

  I did the test again with fermitools 1.2.23 and the error no more apear .

Thanks for the fix,
   David Landriu
