### ISSUE TITLE
core dump sent by gtsrcmaps from fermitools 1.1.7

### ISSUE THREAD

**Issue by landriu** [fermi-lat/Fermitools-conda#48]
Hello,

   I meet a problem on gtsrcmaps with fermitools development version 1.1.7

I get the following error message :

 [landriu@sappcfermi] ~/dev/testGtSrcMaps/testTH > which gtsrcmaps
 /dsm/saplxglast/glast/fermitools/1.1.7/bin/fermitools/gtsrcmaps

 [landriu@sappcfermi] ~/dev/testGtSrcMaps/testTH > gtsrcmaps
 scfile=ft2_july09_pass8.fits expcube=ltCube_105.fits cmap=count_cube_1_E3.fits
 srcmdl=srcModel_1_E3.xml-initial bexpmap=binned_exposure_E3.fits 
 outfile=srcMap_1_E3.fits irfs=CALDB ptsrc=no chatter=4

 WARNING: version mismatch between CFITSIO header (v3.43) and linked library
 (v3.41).

 This is gtsrcmaps version HEAD
 ResponseFunctions::load: IRF used: P8R2_SOURCE_V6
   event_types:  0  1
 Exception en point flottant (core dumped)

.../...

 as the command is working with installed version fermitools 1.0.10 :

 [landriu@sappcfermi] ~/dev/testGtSrcMaps/testTH > which gtsrcmaps 
 /dsm/saplxglast/glast/fermitools/1.0.10/bin/fermitools/gtsrcmaps

 [landriu@sappcfermi] ~/dev/testGtSrcMaps/testTH > gtsrcmaps
 scfile=ft2_july09_pass8.fits expcube=ltCube_105.fits cmap=count_cube_1_E3.fits
 srcmdl=srcModel_1_E3.xml-initial bexpmap=binned_exposure_E3.fits 
 outfile=srcMap_1_E3.fits irfs=CALDB ptsrc=no chatter=4

 WARNING: version mismatch between CFITSIO header (v3.43) and linked library
 (v3.41).

 This is gtsrcmaps version HEAD
 ResponseFunctions::load: IRF used: P8R2_SOURCE_V6
   event_types:  0  1
 Creating source named eg_v02
 Generating SourceMap for eg_v02
 resampling factor: 2
 mapsize: 150
 ..........
 resampling factor: 2
 mapsize: 150
 ..........!
 appending map for eg_v02

 [landriu@sappcfermi] ~/dev/testGtSrcMaps/testTH >

.../...

   and it is working also with the former ScienceTools-01 versions.

 These are small size data chosen for only one day, intended for quick tests .
 
 I put the files on following location :

               ftp://ftp.cea.fr/incoming/y2k01/testGtSrcMaps

 if you want to check if the error still occur on your side :

  ft2_july09_pass8.fits
  isotropic_iem_v02.txt
  ltCube_105.fits
  srcModel_1_E3.xml-initial
  count_cube_1_E3.fits
  binned_exposure_E3.fits

 Thank you for your help,

   Cheers,

    David Landriu

**Comment by donhorner** [comment]
It works for me using the Mac version (1.1.7 or 1.2.1), but I get the same error on Linux with either 1.1.7 or 1.2.1.  @jasercion is looking into it.

**Comment by jasercion** [comment]
Going through this a bit with GDB it looks like the program is specifically throwing an arithmetic exception with the Likelihood::Drm::Drm function:

`Exposure hypercube file[ltCube_105.fits] 
Counts map file[count_cube_1_E3.fits] 
Source model file[srcModel_1_E3.xml-initial] 
Binned exposure map[binned_exposure_E3.fits] 
Source maps output file[srcMap_1_E3.fits] 
Response functions[CALDB] 

Program received signal SIGFPE, Arithmetic exception.
0x00007ffff7bfbafe in Likelihood::Drm::Drm (this=0x21e7cc0, ra=100.97499999982016, dec=20.652200000335483, observation=..., energies=..., edisp_bins=0)
   from /local/data/glitz1/gssctest/miniconda2/envs/fermitools-1_2_3/bin/fermitools/../../lib/fermitools/libLikelihood.so`

https://github.com/fermi-lat/Likelihood/blob/master/src/Drm.cxx

Function begins at Line 44.

Will ask Eric to take a look at this.

**Comment by jasercion** [comment]
@eacharles Let me know if you need a copy of the input files.  I have them saved locally.

**Comment by eacharles** [comment]
Ok, this is happening b/c the test analysis only has one energy bin and precomputing the variables needed to extrapolate the drm is trying to take derivatives and runs off the ends of the energy vector. 
Likelihood ft_conda_48 fixes this.

**Comment by jasercion** [comment]
All changes in the ft_conda_48 branch exist in the master branch so I assume this is fixed.  @landriu can you please verify in 

`conda install -c conda-forge -c fermi -c fermi/label/dev fermitools=1.3.4`

**Comment by landriu** [comment]
I did : 

[landriu@sappcfermi] ~/dev/testGtSrcMaps/testTH > conda activate fermi-1.3.5
(fermi-1.3.5) 
[landriu@sappcfermi] ~/dev/testGtSrcMaps/testTH > gtsrcmaps scfile=ft2_july09_pass8.fits expcube=ltCube_105.fits cmap=count_cube_1_E3.fits srcmdl=srcModel_1_E3.xml-initial bexpmap=binned_exposure_E3.fits wmap=none outfile=srcMap_1_E3.fits irfs=CALDB ptsrc=no chatter=4
This is gtsrcmaps version HEAD
ResponseFunctions::load: IRF used: P8R2_SOURCE_V6
  event_types:  0  1
Creating source named eg_v02
Generating SourceMap for eg_v02 2
resampling factor: 2
mapsize: 150
..........
resampling factor: 2
mapsize: 150
..........!
appending map for eg_v02
(fermi-1.3.5) 

  The problem has been fixed at least for the version 1.3.5 of fermi.

Thanks
