### ISSUE TITLE
are older versions of Fermi tools available via conda?

### ISSUE THREAD

**Issue by cosimoNigro** [fermi-lat/Fermitools-conda#49]
Hello,

following the instruction in the wiki, I was trying to install an older version of the fermitools. The command you specify to do so
```
conda install -c conda-forge/label/cf201901 -c fermi fermitools=<VERSION>
```
works only if `<VERSION>` is replaced with the current release 1.2.1; any older release produces the error:

```
Solving environment: failed
PackagesNotFoundError: The following packages are not available from current channels:
  - fermitools=1.1.8
```

Am I doing something wrong?
Thanks for your support!

**Comment by donhorner** [comment]
The 1.1.X version aren't official releases, so to install one of the you need to specify a label, like "-c fermi/label/dev".  You can read more details in the [Testing Page](https://github.com/fermi-lat/Fermitools-conda/wiki/Testing-the-Fermitools).  You can actually see all the version available in our [Anaconda Cloud](https://anaconda.org/fermi/fermitools/files).

**Comment by cosimoNigro** [comment]
Thanks it worked,
 I think you should specify it in the wiki
https://github.com/fermi-lat/Fermitools-conda/wiki/Installation-Instructions#obtaining-a-specific-version
to use 
```
conda install -c conda-forge/label/cf201901 -c fermi/label/dev fermitools=<VERSION>
```
in order to obtain older versions.
The current instruction is not correct.
Cheers,

**Comment by donhorner** [comment]
Again, the 1.1.X aren't official releases, and we don't encourage people to use them unless they have a specific purpose for testing.  The command would work fine if you put in version 1.0.10, the last official release.
