### ISSUE TITLE
Fermitools 1.2.1 broken on RHEL6

### ISSUE THREAD

**Issue by donhorner** [fermi-lat/Fermitools-conda#50]
The latest release 1.2.1 seems to be broken on RHEL6 systems.  Trying to run a tool just prints out errors like:

>gtbin: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by gtbin)

@jasercion is working on a fix.  This wasn't a problem on the 1.1.7 dev version.

**Comment by limyansky** [comment]
I see an identical error when using fermitools 1.2.1 on CentOS 6.8.

**Comment by donhorner** [comment]
@limyansky We have a test version that works on RHEL6.  You can try it and see if it works on your CentOS system.  I would suggest creating a new environment for it.  You can install it with the following command (I've call the new environment fermi_dev):

conda create -n fermi_dev -c conda-forge/label/cf201901 -c fermi/label/dev -c fermi fermitools=1.2.2

You can find more instructions for setting up test environments in [Testing the Fermitools](https://github.com/fermi-lat/Fermitools-conda/wiki/Testing-the-Fermitools).

**Comment by limyansky** [comment]
@donhorner This version looks like it fixed my issues, thank you!

**Comment by donhorner** [comment]
Great! Hopefully, we'll have an official patch release (which will include some other fixes) out soon.

**Comment by tburnett** [comment]
My case may not be the same, but I get this message:
rhel6-64b:~/guburnett[544]$conda activate fermi
root: error while loading shared libraries: libicui18n.so.56: cannot open shared object file: No such file or directory

I see that there is a file (actually a link): /nfs/farm/g/glast/u/burnett/anaconda2/envs/fermi/lib/libicui18n.so.58
I wonder where the code is that generates this. The error seems to prevent it from adding ANY entries to LD_LIBRARY_PATH.  Anyway, I'll try adding a link with 56.

**Comment by tburnett** [comment]
That didn't work--had to do two more links, then failed with this:
root: symbol lookup error: /nfs/farm/g/glast/u/burnett/anaconda2/envs/fermi/bin/../lib/./libxml2.so.2: undefined symbol: UCNV_TO_U_CALLBACK_STOP_56 . 
So could not fool it into thinking it had version 56. 

Nor did switching to 1.2.2, or 1.1.7. In those cases, LD_LIBRARY_PATH is not set at all with no message.
All I need is to have LD_LIBRARY_PATH set before starting IPython. Is there a script that I can work with?

**Comment by jasercion** [comment]
Workaround found for RHEL6 builds.
