### ISSUE TITLE
Yet another energy dispersion issue (use_edisp returns False), in 1.2.1

### ISSUE THREAD

**Issue by mireianievas** [fermi-lat/Fermitools-conda#53]
I am failing miserably to perform some analysis using energy dispersion corrections and I suspect that is the reason why the fits I get in LAT don't make much sense lately.

I have a BinnedObs instance called Obs and a BinnedAnalysis instance called Fit.

I try to enable the energy dispersion corrections by running

`Fit.logLike.set_edisp_flag(True)`

and right in the next line, I make sure they are properly enabled by executing 

`print("Is edisp enabled? {0}".format(str(Fit.logLike.use_edisp())))`

To my surprise, that returns a False. Am I doing something wrong?

**Comment by phbruel** [comment]
Since the introduction of the edisp_bins mechanism, the trick is to pass the energy dispersion information through a BinnedConfig objet. For instance:
myconf = BinnedConfig(edisp_bins=-1)
blike = binnedAnalysis(...,config=myconf)

**Comment by mireianievas** [comment]
Thank you, I will give it a try.

**Comment by mireianievas** [comment]
Seems to be working.
