### ISSUE TITLE
PASS8R3 IRFs and 4FGL not in 1.2.1?

### ISSUE THREAD

**Issue by AvaGhadimi** [fermi-lat/Fermitools-conda#54]
I have the latest version (1.2.1) of fermitools but when I tried to run an analysis using PASS8R3 IRFs and the 4FGL catalog, I get prompted that the files don't exist.

Are these not included in the new release or do I need to separately download and add them? If the latter, how would I go about doing that?

**Comment by nmirabal** [comment]
Have you followed the Fermi analysis threads?
https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/binned_likelihood_tutorial.html

**Comment by AvaGhadimi** [comment]
Thank you for the link. I'm very new to this so I didn't know where to download the irfs or how to generate the XML models. I'll mark this issue as closed.
