### ISSUE TITLE
Include spectral all models define in likelihood package in the pyLikelihood interface. 

### ISSUE THREAD

**Issue by eacharles** [fermi-lat/Fermitools-conda#66]
Following the instructions here:

https://github.com/fermi-lat/Fermitools-conda/wiki/Contributing-to-the-Fermitools#pylikelihood

**Comment by jasercion** [comment]
@donhorner Do we have documentation anywhere that lists all valid spectral models that should be accessible in Likelihood?

**Comment by donhorner** [comment]
https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/source_models.html

**Comment by jasercion** [comment]
The dev build `fermitools=2.0.6` should have all models in Likelihood implemented in pyLikelihood with the exception of SmoothDoubleBrokenPowerLaw, which is throwing an error at compile time.  Currently debugging that issue and will post an update when finished.

**Comment by jasercion** [comment]
Ok, all models available in Likelihood should (hopefully) be available now in pyLikelihood as of the most recent `fermitools=2.0.6` dev build.  @donhorner would you mind pinging someone to verify this?  It can be installed in a python3 environment using the command:

`conda install -c conda-forge -c fermi/label/dev fermitools=2.0.6`

**Comment by donhorner** [comment]
I tested 2.0.6 and the missing Likelihood model all seem to be in pyLikelihood now.  I was able to stick them in the input XML file, and pylike was able to run a fit. Mis-naming a parameter in the XML file causes the fit to fail with a parameter not found error, so it definitely seems to be calling the model definitions in the code.
