### ISSUE TITLE
xml related warning message in FermiTools 1.9.4

### ISSUE THREAD

**Issue by phbruel** [fermi-lat/Fermitools-conda#71]
I get what seems warning messages when creating a standard binnedAnalysis.
Using a xml file containing only one source:
<?xml version="1.0" standalone="no"?>
<source_library title="source library">
  <source name="PSR4FGL J0835.3-4510" type="PointSource">
    <spectrum type="PLSuperExpCutoff2" apply_edisp="true">
      <parameter free="1" max="10000.000000" min="1e-20" name="Prefactor" scale="1e-08" value="0.292322" />
      <parameter free="1" max="0.000000" min="-9.000000" name="Index1" scale="1" value="-1.21478" />
      <parameter free="0" max="30000.000000" min="1.000000" name="Scale" scale="1" value="1760.38" />
      <parameter free="1" max="100.000000" min="-1.000000" name="Expfactor" scale="0.001" value="23.0406" />
      <parameter free="0" max="5.000000" min="0.000000" name="Index2" scale="1.0" value="0.574389" />
    </spectrum>
    <spatialModel type="SkyDirFunction">
      <parameter free="0" max="360" min="-360" name="RA" scale="1" value="128.835876" />
      <parameter free="0" max="90" min="-90" name="DEC" scale="1" value="-45.176353" />
    </spatialModel>
  </source>
</source_library>I create the following binnedAnalysis:
myconf = BinnedConfig(edisp_bins=-1)
blike = binnedAnalysis(irfs='CALDB',
                       expcube='out_gtltcube.fits',
                       srcmdl='model_4FGL_edisp_onesrc.xml',
                       optimizer='MINUIT',
                       cmap='out_gtsrcmaps_edisp_4FGL.fits',
                       wmap='/nfs/farm/g/glast/g/pulsar/gtsrcmapsWeights/Scripts/DataE2XWgts_3percent_P305_zmax105_10years.fits',
                       bexpmap='out_gtexpcube2_edisp_4FGL.fits',
                       config=myconf)I get the following message
Did not set xml attribute for nested source: name : PSR4FGL J0835.3-4510
Did not set xml attribute for nested source: type : PointSourceWhen using an xml file with more than one source, I get the same message for all sources.
What is surprising is that the fit seems to work fine, so the messages seem to be simple warning messages. Anyway, it seems wise to try to make them disappear.

**Comment by dagorym** [comment]
This is should be fixed in 1.9.6

**Comment by donhorner** [comment]
@phbruel Can you check this with the latest betas and confirm that it has been fixed?

**Comment by phbruel** [comment]
I've performed a test with 1.9.13 and I confirm that I don't see the problem anymore.

**Comment by jasercion** [comment]
Closing issue.
