### ISSUE TITLE
P8R3_V3 IRFs are missing in FermiTools 1.9.4

### ISSUE THREAD

**Issue by phbruel** [fermi-lat/Fermitools-conda#72]
The new IRFs (P8R3_V3) are not available in 1.9.4.

gtirfs | grep P8R3 | grep ULTRACLEANVETO
P8R3_ULTRACLEANVETO_V2 ( = P8R3_ULTRACLEANVETO_V2::BACK + P8R3_ULTRACLEANVETO_V2::FRONT )
P8R3_ULTRACLEANVETO_V2 (EDISP) ( = P8R3_ULTRACLEANVETO_V2::EDISP0 + P8R3_ULTRACLEANVETO_V2::EDISP1 + P8R3_ULTRACLEANVETO_V2::EDISP2 + P8R3_ULTRACLEANVETO_V2::EDISP3 )
P8R3_ULTRACLEANVETO_V2 (PSF) ( = P8R3_ULTRACLEANVETO_V2::PSF0 + P8R3_ULTRACLEANVETO_V2::PSF1 + P8R3_ULTRACLEANVETO_V2::PSF2 + P8R3_ULTRACLEANVETO_V2::PSF3 )
P8R3_ULTRACLEANVETO_V2::BACK
P8R3_ULTRACLEANVETO_V2::EDISP0
P8R3_ULTRACLEANVETO_V2::EDISP1
P8R3_ULTRACLEANVETO_V2::EDISP2
P8R3_ULTRACLEANVETO_V2::EDISP3
P8R3_ULTRACLEANVETO_V2::FRONT
P8R3_ULTRACLEANVETO_V2::PSF0
P8R3_ULTRACLEANVETO_V2::PSF1
P8R3_ULTRACLEANVETO_V2::PSF2
P8R3_ULTRACLEANVETO_V2::PSF3

When running the same command with FermiTools 1.7.1, I get:
gtirfs | grep P8R3 | grep ULTRACLEANVETO
P8R3_ULTRACLEANVETO_V2 ( = P8R3_ULTRACLEANVETO_V2::BACK + P8R3_ULTRACLEANVETO_V2::FRONT )
P8R3_ULTRACLEANVETO_V2 (EDISP) ( = P8R3_ULTRACLEANVETO_V2::EDISP0 + P8R3_ULTRACLEANVETO_V2::EDISP1 + P8R3_ULTRACLEANVETO_V2::EDISP2 + P8R3_ULTRACLEANVETO_V2::EDISP3 )
P8R3_ULTRACLEANVETO_V2 (PSF) ( = P8R3_ULTRACLEANVETO_V2::PSF0 + P8R3_ULTRACLEANVETO_V2::PSF1 + P8R3_ULTRACLEANVETO_V2::PSF2 + P8R3_ULTRACLEANVETO_V2::PSF3 )
P8R3_ULTRACLEANVETO_V2::BACK
P8R3_ULTRACLEANVETO_V2::EDISP0
P8R3_ULTRACLEANVETO_V2::EDISP1
P8R3_ULTRACLEANVETO_V2::EDISP2
P8R3_ULTRACLEANVETO_V2::EDISP3
P8R3_ULTRACLEANVETO_V2::FRONT
P8R3_ULTRACLEANVETO_V2::PSF0
P8R3_ULTRACLEANVETO_V2::PSF1
P8R3_ULTRACLEANVETO_V2::PSF2
P8R3_ULTRACLEANVETO_V2::PSF3
P8R3_ULTRACLEANVETO_V3 ( = P8R3_ULTRACLEANVETO_V3::BACK + P8R3_ULTRACLEANVETO_V3::FRONT )
P8R3_ULTRACLEANVETO_V3 (EDISP) ( = P8R3_ULTRACLEANVETO_V3::EDISP0 + P8R3_ULTRACLEANVETO_V3::EDISP1 + P8R3_ULTRACLEANVETO_V3::EDISP2 + P8R3_ULTRACLEANVETO_V3::EDISP3 )
P8R3_ULTRACLEANVETO_V3 (PSF) ( = P8R3_ULTRACLEANVETO_V3::PSF0 + P8R3_ULTRACLEANVETO_V3::PSF1 + P8R3_ULTRACLEANVETO_V3::PSF2 + P8R3_ULTRACLEANVETO_V3::PSF3 )
P8R3_ULTRACLEANVETO_V3::BACK
P8R3_ULTRACLEANVETO_V3::EDISP0
P8R3_ULTRACLEANVETO_V3::EDISP1
P8R3_ULTRACLEANVETO_V3::EDISP2
P8R3_ULTRACLEANVETO_V3::EDISP3
P8R3_ULTRACLEANVETO_V3::FRONT
P8R3_ULTRACLEANVETO_V3::PSF0
P8R3_ULTRACLEANVETO_V3::PSF1
P8R3_ULTRACLEANVETO_V3::PSF2
P8R3_ULTRACLEANVETO_V3::PSF3

**Comment by donhorner** [comment]
I'm closing this issue since the IRFs seem to be present.
