### ISSUE TITLE
Need ncurses version requirement.

### ISSUE THREAD

**Issue by kialio** [fermi-lat/Fermitools-conda#8]
Ncurses needs to be <6.0.  If I have the newest ncurses I get this:

`
In [1]: import pyLikelihood as pyLike
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-99f42f61c6a8> in <module>()
----> 1 import pyLikelihood as pyLike

/usr/local/anaconda3/envs/fermi/lib/python2.7/site-packages/fermitools/pyLikelihood.py in <module>()
     15         except ImportError:
     16             return importlib.import_module('_pyLikelihood')
---> 17     _pyLikelihood = swig_import_helper()
     18     del swig_import_helper
     19 elif _swig_python_version_info >= (2, 6, 0):

/usr/local/anaconda3/envs/fermi/lib/python2.7/site-packages/fermitools/pyLikelihood.py in swig_import_helper()
     14             return importlib.import_module(mname)
     15         except ImportError:
---> 16             return importlib.import_module('_pyLikelihood')
     17     _pyLikelihood = swig_import_helper()
     18     del swig_import_helper

/usr/local/anaconda3/envs/fermi/lib/python2.7/importlib/__init__.pyc in import_module(name, package)
     35             level += 1
     36         name = _resolve_name(name[level:], package, level)
---> 37     __import__(name)
     38     return sys.modules[name]

ImportError: dlopen(/usr/local/anaconda3/envs/fermi/lib/fermitools/_pyLikelihood.so, 2): Library not loaded: @rpath/libtinfo.5.dylib
  Referenced from: /usr/local/anaconda3/envs/fermi/lib/fermitools/_pyLikelihood.so
  Reason: image not found
`
If I downgrade to ncurses 5 (conda install "ncurses<6.0") then pyLikelihood imports fine.

**Comment by jasercion** [comment]
I'll pin this in the meta.yaml.

**Comment by jasercion** [comment]
Fix branch: https://github.com/fermi-lat/ScienceTools-conda-recipe/tree/ncurses_pin

Once tested I'll merge the change

**Comment by jasercion** [comment]
@kialio It looks like it is fixed.  Please verify after updating to Fermitools=1.0.0 and if everything looks good I'll close out the issue.

**Comment by jasercion** [comment]
Closing out.  Please reopen if this crops up again.
