### ISSUE TITLE
Problem running gtlike 

### ISSUE THREAD

**Issue by lauramog** [fermi-lat/Fermitools-conda#90]
Caught N3tip12TipExceptionE at the top level: Cannot read keyword "NDSKEYS" in file "binned_srcmaps.fits" (CFITSIO ERROR 202: keyword not found in header)

I have this problem running gtlike. can someone help me?
thanks!

**Comment by lauramog** [comment]
Prior to this error I have a warning runnirg  gtsrcmaps :
Caught N10facilities14UntranslatableE at the top level: LATEXTDIR

help, please!!

**Comment by nmirabal** [comment]
Do you have the latest version of the Fermitools?. 
https://github.com/fermi-lat/Fermitools-conda/wiki/Quickstart-Guide

Can you check whether you can run the following analysis thread 
 https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/binned_likelihood_tutorial.html

**Comment by lauramog** [comment]
> Do you have the latest version of the Fermitools?.
> https://github.com/fermi-lat/Fermitools-conda/wiki/Quickstart-Guide
> 
> Can you check whether you can run the following analysis thread
> https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/binned_likelihood_tutorial.html

I ran the binned analysis with the files of the example, but I had a problem with gtlike:
the message was: 
Computing TS values for each source (218 total)
........................................................................................Caught N10optimizers11OutOfBoundsE at the top level: Attempt to set the value outside of existing bounds.

3C279_binned_output.xml wasn't generated.

**Comment by nmirabal** [comment]
Unfortunately, I haven't been able to reproduce this issue. My suggestion  is to  download the latest fermitools that was just released and try again. You can start with the event and spacecraft files but run each step in the analysis thread in your OS. Here are the instructions on how to upgrade the fermitools 
https://github.com/fermi-lat/Fermitools-conda/wiki/Quickstart-Guide

**Comment by lauramog** [comment]
> Unfortunately, I haven't been able to reproduce this issue. My suggestion is to download the latest fermitools that was just released and try again. You can start with the event and spacecraft files but run each step in the analysis thread in your OS. Here are the instructions on how to upgrade the fermitools
> https://github.com/fermi-lat/Fermitools-conda/wiki/Quickstart-Guide

Okay, I'm working on it. thanks for your help!!
