### ISSUE TITLE
conda install fails

### ISSUE THREAD

**Issue by paulray** [fermi-lat/Fermitools-conda#91]
Hi,

Just tried to install fermitools using conda for the first time (I was waiting for Python 3 support). It fails and I have no idea why. Here is the key info on my CentOS 7 system

```
% conda create -n fermi -c conda-forge -c fermi fermitools
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                           

UnsatisfiableError: 
Note that strict channel priority may have removed packages required for satisfiability.

% conda info

     active environment : None
            shell level : 0
       user config file : /home/paulr/.condarc
 populated config files : /home/paulr/.condarc
          conda version : 4.8.5
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.17
       base environment : /Software/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Software/miniconda3/pkgs
                          /home/paulr/.conda/pkgs
       envs directories : /Software/miniconda3/envs
                          /home/paulr/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.5 requests/2.24.0 CPython/3.7.6 Linux/3.10.0-1127.19.1.el7.x86_64 centos/7.8.2003 glibc/2.17
                UID:GID : 7655:7650
             netrc file : None
           offline mode : False

% uname -a
Linux heselin0.nrl.navy.mil 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by lauramog** [comment]
I am facing the same issue, I uninstalled fermitools due a problem running a binned likelihood Analysis, and try to install it again and I have the same problem as you:


Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                      

UnsatisfiableError: 
Note that strict channel priority may have removed packages required for satisfiability.

**Comment by paulray** [comment]
I've been playing with this, and I saw the note about channel priority, so I changed the channel priority from "strict" to "flexible" in  my .condarc.  Now it seems to work. At least I was able to create and activate the channel and gtbin runs!

**Comment by lauramog** [comment]
> I've been playing with this, and I saw the note about channel priority, so I changed the channel priority from "strict" to "flexible" in my .condarc. Now it seems to work. At least I was able to create and activate the channel and gtbin runs!

I'm. going to try it.  Thanks for reply!

**Comment by donhorner** [comment]
I'm glad you found a workaround.  We'll add this to the FSSC's list of things to investigate.

**Comment by jasercion** [comment]
Hi @paulray, I'm unable to replicate this problem in a clean centos7 container.  Did you have this issue on any other machines by any chance?

**Comment by paulray** [comment]
No, sorry. I've only installed it on that one machine. I could try on my Mac, but I doubt that would be illuminating.  I'll let you know if I see it again.

**Comment by jasercion** [comment]
@lauramog Were you also using a CentOS7 machine?

**Comment by jasercion** [comment]
> No, sorry. I've only installed it on that one machine. I could try on my Mac, but I doubt that would be illuminating. I'll let you know if I see it again.

Thanks!

**Comment by basuparth** [comment]
Ran into the same error on Ubuntu 20.04. conda first fails with frozen solve then automatically shifts to flexible solve but with no effect. I also tried setting the channel to flexible from the outset but with no avail. Downgrading conda versions to 4.6 etc also don't work. Incidentally I faced no problem while installing the Gravitational wave analysis environment using igwn-py37.yaml by executing  conda env create --file igwn-py37.yaml. All the packages were installed without any errors,warnings or "hiccups".

My system specs
OS - Ubuntu 20.04(fresh install not an upgrade)
Anaconda  2020.07(also tried with previous versions from 2019 for both anaconda 2 and 3 and previously known compatible fermi versions with those anaconda installations respectively).

Please let me know if anything resolves this issue.

[fermi_conda_installation_issue.txt](https://github.com/fermi-lat/Fermitools-conda/files/5540207/fermi_conda_installation_issue.txt)

**Comment by donhorner** [comment]
@basuparth  According to your log, you are trying to install version 1.0.10.  That's a rather old version.  Is that what you mean to do?  If so, you will also need to use the cf201901 label as described here:  https://github.com/fermi-lat/Fermitools-conda/wiki/Installation-Instructions#downgrading

**Comment by basuparth** [comment]
Oh Sorry, I didn't mean to attach this log. I got the older 1.0.10 version installed by adding the cf201901 later(really sorry about not adding an update/edit sooner), but the recent version 2.0.0  could not be installed successfully on Ubuntu 20.04.1. I downgraded the version to Ubuntu 18.04 but the conda-forge channel kept trying to resolve the environment for over 4 hrs after which I terminated the process. I tried installing 1.2.23 using label cf202003 which succeeded as well. It's just the version 2.0.0 which is proving problematic.

**Comment by jasercion** [comment]
Hi @basuparth, this seems to be a dependency resolution issue.  I'm working on tracking it down but could you please try this command to create the environment/install the python3 tools and let me know if it works on your machine?

`conda create -n fermi -c conda-forge -c fermi fermitools python=3`

Manually specifying the python version seems to solve the problem.

**Comment by basuparth** [comment]
Thanks, @jasercion this solves the problem.
