### ISSUE TITLE
Installing Fermitools in python 3.

### ISSUE THREAD

**Issue by lauramog** [fermi-lat/Fermitools-conda#93]
I'm installing fermitools via conda: 
conda create -n fermi -c conda-forge/label/cf201901 -c fermi fermitools
 In MacOS,  which has by default has python 2.7.

So, I try install it in python 3 in differents way: 
conda create -n fermi -c conda-forge -c fermi fermitools  python=3
conda create -n fermi -c conda-forge -c fermi fermitools  python=3.7

but when I check with -conda info-, it was installed in python=2.7

I also tried crating a virtual enviroment with python 3, using    conda create -n ipykernel_py2 python=3 ipykernel
and inside this I installed fermitools, but it is also installes with python 2.7.

I would appreciate any idea or suggestion to fix it.

**Comment by donhorner** [comment]
What does 'conda list python' tell you when you have the fermi environment activated?  Or 'python --version'?  I think 'conda info' is telling you what version of python conda was installed with (via anaconda or miniconda).  That doesn't matter for the Fermitools, conda will install python3 if needed. 

Also, you shouldn't use the cf201901 label to install Fermitools 2.0, just 'conda create -n fermi -c conda-forge -c fermi fermitools '.

**Comment by lauramog** [comment]
> What does 'conda list python' tell you when you have the fermi environment activated? Or 'python --version'? I think 'conda info' is telling you what version of python conda was installed with (via anaconda or miniconda). That doesn't matter for the Fermitools, conda will install python3 if needed.
> 
> Also, you shouldn't use the cf201901 label to install Fermitools 2.0, just 'conda create -n fermi -c conda-forge -c fermi fermitools '.

Yes, I just realized when I check python --version it is  3.7.8.
Thanks for reply so soon.
