### ISSUE TITLE
Problem with gtexpcube2. new version of Fermitools

### ISSUE THREAD

**Issue by KenAnderson84** [fermi-lat/Fermitools-conda#94]
Hello,

I'm just install the new version of Fermitools in python 3, I'm probing it with the Binned Likelihood Analysis (https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/binned_likelihood_tutorial.html), but I  found an  error with gtexpcube2, 

Caught St13runtime_error at the top level: Invalid IRF name: P8R3_SOURCE_V3

I have tried with other names (  iso_P8R3_SOURCE_V3_v1.txt, P8R3_SOURCE_V3_v1)
 I'm always getting the same issue: 
Caught St13runtime_error at the top level: Invalid IRF name:

**Comment by jasercion** [comment]
Hi @KenAnderson84,

Just to clarify, is the error readout saying `Invalid IRF name: P8R3_SOURCE_V3` or `Invalid IRF name: ` (ending with a blank space)?

**Comment by KenAnderson84** [comment]
> Hi @KenAnderson84,
> 
> Just to clarify, is the error readout saying `Invalid IRF name: P8R3_SOURCE_V3` or `Invalid IRF name: ` (ending with a blank space)?

Hi, thanks for reply.
the error is: Invalid IRF name: P8R3_SOURCE_V3  (ending with  P8R3_SOURCE_V3  )

**Comment by jasercion** [comment]
Hi @KenAnderson84, apologies for the late response.  This should be fixed in our latest release.  Would you mind updating to `Fermitools=2.0.0` and letting me know if the problem still occurs?

**Comment by jasercion** [comment]
I have been unable to replicate this in my own testing.
