### ISSUE TITLE
Attempt to set the value outside of existing bounds.

### ISSUE THREAD

**Issue by laofei177** [fermi-lat/Fermitools-conda#98]
Computing TS values for each source (627 total)
.............................................................................Caught N10optimizers11OutOfBoundsE at the top level: Attempt to set the value outside of existing bounds.

What's the reason caused this?How to do it?

**Comment by nmirabal** [comment]
Fitting faint sources can cause this type of issue. You can use make4FGLxml.py to fix all source parameters for faint sources below a certain TS value. Try the -s argument in make4FGLxml.py  as explained at the end of the file
https://fermi.gsfc.nasa.gov/ssc/data/analysis/user/python3/make4FGLxml.py

**Comment by laofei177** [comment]
@nmirabal  here I sincerely express my thanks.
